// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

val CLUSTERS =
    CLUSTERS_1_0 +
        CLUSTERS_1_2 +
        CLUSTERS_1_3 +
        CLUSTERS_1_4 +
        CLUSTERS_1_5 +
        CLUSTERS_1_6 +
        CLUSTERS_1_7
