// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

val CLUSTERS_1_7 =
    mapOf<ClusterId, ClusterInfo>(
        Clusters.ThermostatMode.ID to
            ClusterInfo(
                name = "Thermostat Mode",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.ThermostatMode.Attributes.SupportedModes.ID to
                            AttributeInfo(
                                name = "SupportedModes",
                                type = DataType.UNKNOWN,
                            ),
                        Clusters.ThermostatMode.Attributes.CurrentMode.ID to
                            AttributeInfo(
                                name = "CurrentMode",
                                type = DataType.UNKNOWN,
                            ),
                        Clusters.ThermostatMode.Attributes.StartUpMode.ID to
                            AttributeInfo(
                                name = "StartUpMode",
                                type = DataType.UNKNOWN,
                            ),
                        Clusters.ThermostatMode.Attributes.OnMode.ID to
                            AttributeInfo(
                                name = "OnMode",
                                type = DataType.UNKNOWN,
                            ),
                        Clusters.ThermostatMode.Attributes.CoreModeTags.ID to
                            AttributeInfo(
                                name = "CoreModeTags",
                                type = DataType.UNKNOWN,
                            ),
                    ),
                commandsIncoming = mapOf<CommandId, CommandInfo>(),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.ElectricalAlarm.ID to
            ClusterInfo(
                name = "Electrical Alarm",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.ElectricalAlarm.Attributes.OverVoltageThreshold.ID to
                            AttributeInfo(
                                name = "OverVoltageThreshold",
                                type = DataType.VOLTAGE_MILLIVOLTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.UnderVoltageThreshold.ID to
                            AttributeInfo(
                                name = "UnderVoltageThreshold",
                                type = DataType.VOLTAGE_MILLIVOLTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.OverFrequencyThreshold.ID to
                            AttributeInfo(
                                name = "OverFrequencyThreshold",
                                type = DataType.INT64,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.UnderFrequencyThreshold.ID to
                            AttributeInfo(
                                name = "UnderFrequencyThreshold",
                                type = DataType.INT64,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.OverPowerThreshold.ID to
                            AttributeInfo(
                                name = "OverPowerThreshold",
                                type = DataType.POWER_MILLIWATTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.UnderPowerThreshold.ID to
                            AttributeInfo(
                                name = "UnderPowerThreshold",
                                type = DataType.POWER_MILLIWATTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.OverCurrentThreshold.ID to
                            AttributeInfo(
                                name = "OverCurrentThreshold",
                                type = DataType.AMPERAGE_MILLIAMPERES,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.UnderCurrentThreshold.ID to
                            AttributeInfo(
                                name = "UnderCurrentThreshold",
                                type = DataType.AMPERAGE_MILLIAMPERES,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.PowerImportThreshold.ID to
                            AttributeInfo(
                                name = "PowerImportThreshold",
                                type = DataType.POWER_MILLIWATTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalAlarm.Attributes.PowerExportThreshold.ID to
                            AttributeInfo(
                                name = "PowerExportThreshold",
                                type = DataType.POWER_MILLIWATTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.ElectricalAlarm.CommandsIncoming.SetElectricalAlarmThresholds.ID to
                            CommandInfo(
                                name = "SetElectricalAlarmThresholds",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "OverVoltageThreshold",
                                                type = DataType.VOLTAGE_MILLIVOLTS,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "UnderVoltageThreshold",
                                                type = DataType.VOLTAGE_MILLIVOLTS,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "OverFrequencyThreshold",
                                                type = DataType.INT64,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "UnderFrequencyThreshold",
                                                type = DataType.INT64,
                                            ),
                                        4u to
                                            ParameterInfo(
                                                name = "OverPowerThreshold",
                                                type = DataType.POWER_MILLIWATTS,
                                            ),
                                        5u to
                                            ParameterInfo(
                                                name = "UnderPowerThreshold",
                                                type = DataType.POWER_MILLIWATTS,
                                            ),
                                        6u to
                                            ParameterInfo(
                                                name = "OverCurrentThreshold",
                                                type = DataType.AMPERAGE_MILLIAMPERES,
                                            ),
                                        7u to
                                            ParameterInfo(
                                                name = "UnderCurrentThreshold",
                                                type = DataType.AMPERAGE_MILLIAMPERES,
                                            ),
                                        8u to
                                            ParameterInfo(
                                                name = "PowerImportThreshold",
                                                type = DataType.POWER_MILLIWATTS,
                                            ),
                                        9u to
                                            ParameterInfo(
                                                name = "PowerExportThreshold",
                                                type = DataType.POWER_MILLIWATTS,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.ElectricalDistribution.ID to
            ClusterInfo(
                name = "Electrical Distribution",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.ElectricalDistribution.Attributes.MaxContinuousCurrent.ID to
                            AttributeInfo(
                                name = "MaxContinuousCurrent",
                                type = DataType.AMPERAGE_MILLIAMPERES,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalDistribution.Attributes.MaxVoltage.ID to
                            AttributeInfo(
                                name = "MaxVoltage",
                                type = DataType.VOLTAGE_MILLIVOLTS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalDistribution.Attributes.NumberOfPoles.ID to
                            AttributeInfo(
                                name = "NumberOfPoles",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalDistribution.Attributes.EndOfLife.ID to
                            AttributeInfo(
                                name = "EndOfLife",
                                type = DataType.ELECTRICAL_DISTRIBUTION_CLUSTER_END_OF_LIFE_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalDistribution.Attributes.ServiceEntranceRated.ID to
                            AttributeInfo(
                                name = "ServiceEntranceRated",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming = mapOf<CommandId, CommandInfo>(),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.ElectricalProtectionAlarm.ID to
            ClusterInfo(
                name = "Electrical Protection Alarm",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.ElectricalProtectionAlarm.Attributes.ArcCause.ID to
                            AttributeInfo(
                                name = "ArcCause",
                                type = DataType.ARC_CAUSE_BITMAP,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalProtectionAlarm.Attributes.OverLoadRating.ID to
                            AttributeInfo(
                                name = "OverLoadRating",
                                type = DataType.OVER_LOAD_RATINGS_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalProtectionAlarm.Attributes.OverVoltageRating.ID to
                            AttributeInfo(
                                name = "OverVoltageRating",
                                type = DataType.OVER_VOLTAGE_RATINGS_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalProtectionAlarm.Attributes.SurgeProtectionRating.ID to
                            AttributeInfo(
                                name = "SurgeProtectionRating",
                                type = DataType.SURGE_PROTECTION_RATINGS_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalProtectionAlarm.Attributes.ShortCircuitRating.ID to
                            AttributeInfo(
                                name = "ShortCircuitRating",
                                type = DataType.SHORT_CIRCUIT_RATINGS_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalProtectionAlarm.Attributes.ResidualCurrentRating.ID to
                            AttributeInfo(
                                name = "ResidualCurrentRating",
                                type = DataType.RESIDUAL_CURRENT_FAULT_RATINGS_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ElectricalProtectionAlarm.Attributes.ArcFaultRating.ID to
                            AttributeInfo(
                                name = "ArcFaultRating",
                                type = DataType.ARC_FAULT_RATINGS_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming = mapOf<CommandId, CommandInfo>(),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.Humidistat.ID to
            ClusterInfo(
                name = "Humidistat",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.Humidistat.Attributes.SupportedModes.ID to
                            AttributeInfo(
                                name = "SupportedModes",
                                type = DataType.LIST_HUMIDISTAT_CLUSTER_MODE_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.Humidistat.Attributes.Mode.ID to
                            AttributeInfo(
                                name = "Mode",
                                type = DataType.HUMIDISTAT_CLUSTER_MODE_ENUM,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.SystemState.ID to
                            AttributeInfo(
                                name = "SystemState",
                                type = DataType.HUMIDISTAT_CLUSTER_SYSTEM_STATE_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.Humidistat.Attributes.UserSetpoint.ID to
                            AttributeInfo(
                                name = "UserSetpoint",
                                type = DataType.PERCENT,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.MinSetpoint.ID to
                            AttributeInfo(
                                name = "MinSetpoint",
                                type = DataType.PERCENT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.Humidistat.Attributes.MaxSetpoint.ID to
                            AttributeInfo(
                                name = "MaxSetpoint",
                                type = DataType.PERCENT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.Humidistat.Attributes.Step.ID to
                            AttributeInfo(
                                name = "Step",
                                type = DataType.PERCENT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.Humidistat.Attributes.TargetSetpoint.ID to
                            AttributeInfo(
                                name = "TargetSetpoint",
                                type = DataType.PERCENT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.Humidistat.Attributes.MistType.ID to
                            AttributeInfo(
                                name = "MistType",
                                type = DataType.MIST_TYPE_BITMAP,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.Continuous.ID to
                            AttributeInfo(
                                name = "Continuous",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.Sleep.ID to
                            AttributeInfo(
                                name = "Sleep",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.Optimal.ID to
                            AttributeInfo(
                                name = "Optimal",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.CondPumpEnabled.ID to
                            AttributeInfo(
                                name = "CondPumpEnabled",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.Humidistat.Attributes.CondRunCount.ID to
                            AttributeInfo(
                                name = "CondRunCount",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.Humidistat.CommandsIncoming.SetSettings.ID to
                            CommandInfo(
                                name = "SetSettings",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "UserSetpoint",
                                                type = DataType.PERCENT,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "Mode",
                                                type = DataType.HUMIDISTAT_CLUSTER_MODE_ENUM,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "MistType",
                                                type = DataType.MIST_TYPE_BITMAP,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "Continuous",
                                                type = DataType.BOOLEAN,
                                            ),
                                        4u to
                                            ParameterInfo(
                                                name = "Sleep",
                                                type = DataType.BOOLEAN,
                                            ),
                                        5u to
                                            ParameterInfo(
                                                name = "Optimal",
                                                type = DataType.BOOLEAN,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.AmbientSensingUnion.ID to
            ClusterInfo(
                name = "Ambient Sensing Union",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.AmbientSensingUnion.Attributes.UnionName.ID to
                            AttributeInfo(
                                name = "UnionName",
                                type = DataType.STRING,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.AmbientSensingUnion.Attributes.UnionHealth.ID to
                            AttributeInfo(
                                name = "UnionHealth",
                                type = DataType.AMBIENT_SENSING_UNION_CLUSTER_UNION_HEALTH_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AmbientSensingUnion.Attributes.UnionContributorList.ID to
                            AttributeInfo(
                                name = "UnionContributorList",
                                type = DataType.LIST_UNION_CONTRIBUTOR_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming = mapOf<CommandId, CommandInfo>(),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events =
                    mapOf<EventId, EventInfo>(
                        Clusters.AmbientSensingUnion.Events.UnionContributorAdded.ID to
                            EventInfo(
                                name = "UnionContributorAdded",
                            ),
                        Clusters.AmbientSensingUnion.Events.UnionContributorRemoved.ID to
                            EventInfo(
                                name = "UnionContributorRemoved",
                            ),
                        Clusters.AmbientSensingUnion.Events.UnionContributorStatusChanged.ID to
                            EventInfo(
                                name = "UnionContributorStatusChanged",
                            ),
                    ),
            ),
        Clusters.ProximityRanging.ID to
            ClusterInfo(
                name = "Proximity Ranging",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.ProximityRanging.Attributes.RangingCapabilities.ID to
                            AttributeInfo(
                                name = "RangingCapabilities",
                                type = DataType.LIST_RANGING_CAPABILITIES_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.WiFiDevIK.ID to
                            AttributeInfo(
                                name = "WiFiDevIK",
                                type = DataType.OCTET_STRING,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.BLEDeviceID.ID to
                            AttributeInfo(
                                name = "BLEDeviceID",
                                type = DataType.U_INT64,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.BLTDevIK.ID to
                            AttributeInfo(
                                name = "BLTDevIK",
                                type = DataType.OCTET_STRING,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.BLTCSSecurityLevel.ID to
                            AttributeInfo(
                                name = "BLTCSSecurityLevel",
                                type = DataType.PROXIMITY_RANGING_CLUSTER_BLTCS_SECURITY_LEVEL_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.BLTCSModeCapability.ID to
                            AttributeInfo(
                                name = "BLTCSModeCapability",
                                type = DataType.PROXIMITY_RANGING_CLUSTER_BLTCS_MODE_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.SessionIDList.ID to
                            AttributeInfo(
                                name = "SessionIDList",
                                type = DataType.LIST_U_INT8,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.ProximityRanging.Attributes.RangingConstraints.ID to
                            AttributeInfo(
                                name = "RangingConstraints",
                                type = DataType.LIST_RANGING_CONSTRAINT_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.ProximityRanging.CommandsIncoming.StartRangingRequest.ID to
                            CommandInfo(
                                name = "StartRangingRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Technology",
                                                type =
                                                    DataType
                                                        .PROXIMITY_RANGING_CLUSTER_RANGING_TECH_ENUM,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "WiFiRangingDeviceRoleConfig",
                                                type =
                                                    DataType
                                                        .WI_FI_RANGING_DEVICE_ROLE_CONFIG_STRUCT,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "BLERangingDeviceRoleConfig",
                                                type =
                                                    DataType.BLE_RANGING_DEVICE_ROLE_CONFIG_STRUCT,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "BLTChannelSoundingDeviceRoleConfig",
                                                type =
                                                    DataType
                                                        .BLT_CHANNEL_SOUNDING_DEVICE_ROLE_CONFIG_STRUCT,
                                            ),
                                        4u to
                                            ParameterInfo(
                                                name = "FrequencyBand",
                                                type = DataType.RADIO_BAND_BITMAP,
                                            ),
                                        5u to
                                            ParameterInfo(
                                                name = "Bandwidth",
                                                type = DataType.RANGING_BANDWIDTH_BITMAP,
                                            ),
                                        6u to
                                            ParameterInfo(
                                                name = "Trigger",
                                                type = DataType.RANGING_TRIGGER_CONDITION_STRUCT,
                                            ),
                                        7u to
                                            ParameterInfo(
                                                name = "ReportingCondition",
                                                type = DataType.REPORTING_CONDITION_STRUCT,
                                            ),
                                    ),
                            ),
                        Clusters.ProximityRanging.CommandsIncoming.StopRangingRequest.ID to
                            CommandInfo(
                                name = "StopRangingRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "SessionID",
                                                type = DataType.U_INT8,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.ProximityRanging.CommandsOutgoing.StartRangingResponse.ID to
                            CommandInfo(
                                name = "StartRangingResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "SessionID",
                                                type = DataType.U_INT8,
                                            ),
                                    ),
                            ),
                    ),
                events =
                    mapOf<EventId, EventInfo>(
                        Clusters.ProximityRanging.Events.RangingResult.ID to
                            EventInfo(
                                name = "RangingResult",
                            ),
                        Clusters.ProximityRanging.Events.RangingSessionStatus.ID to
                            EventInfo(
                                name = "RangingSessionStatus",
                            ),
                    ),
            ),
        Clusters.SmokeConcentrationMeasurement.ID to
            ClusterInfo(
                name = "Smoke Concentration Measurement",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.SmokeConcentrationMeasurement.Attributes.MeasuredValue.ID to
                            AttributeInfo(
                                name = "MeasuredValue",
                                type = DataType.SINGLE,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.MinMeasuredValue.ID to
                            AttributeInfo(
                                name = "MinMeasuredValue",
                                type = DataType.SINGLE,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.MaxMeasuredValue.ID to
                            AttributeInfo(
                                name = "MaxMeasuredValue",
                                type = DataType.SINGLE,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.PeakMeasuredValue.ID to
                            AttributeInfo(
                                name = "PeakMeasuredValue",
                                type = DataType.SINGLE,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.PeakMeasuredValueWindow
                            .ID to
                            AttributeInfo(
                                name = "PeakMeasuredValueWindow",
                                type = DataType.ELAPSED_SECONDS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.AverageMeasuredValue.ID to
                            AttributeInfo(
                                name = "AverageMeasuredValue",
                                type = DataType.SINGLE,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.AverageMeasuredValueWindow
                            .ID to
                            AttributeInfo(
                                name = "AverageMeasuredValueWindow",
                                type = DataType.ELAPSED_SECONDS,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.Uncertainty.ID to
                            AttributeInfo(
                                name = "Uncertainty",
                                type = DataType.SINGLE,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.MeasurementUnit.ID to
                            AttributeInfo(
                                name = "MeasurementUnit",
                                type =
                                    DataType
                                        .CONCENTRATION_MEASUREMENT_CLUSTER_MEASUREMENT_UNIT_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.MeasurementMedium.ID to
                            AttributeInfo(
                                name = "MeasurementMedium",
                                type =
                                    DataType
                                        .CONCENTRATION_MEASUREMENT_CLUSTER_MEASUREMENT_MEDIUM_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.SmokeConcentrationMeasurement.Attributes.LevelValue.ID to
                            AttributeInfo(
                                name = "LevelValue",
                                type = DataType.CONCENTRATION_MEASUREMENT_CLUSTER_LEVEL_VALUE_ENUM,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming = mapOf<CommandId, CommandInfo>(),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.NetworkIdentityManagement.ID to
            ClusterInfo(
                name = "Network Identity Management",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.NetworkIdentityManagement.Attributes.ActiveNetworkIdentities.ID to
                            AttributeInfo(
                                name = "ActiveNetworkIdentities",
                                type = DataType.LIST_ACTIVE_NETWORK_IDENTITY_STRUCT,
                                readPrivilege = Privilege.MANAGE,
                            ),
                        Clusters.NetworkIdentityManagement.Attributes.Clients.ID to
                            AttributeInfo(
                                name = "Clients",
                                type = DataType.LIST_CLIENT_STRUCT,
                                readPrivilege = Privilege.MANAGE,
                            ),
                        Clusters.NetworkIdentityManagement.Attributes.ClientTableSize.ID to
                            AttributeInfo(
                                name = "ClientTableSize",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.NetworkIdentityManagement.CommandsIncoming.AddClient.ID to
                            CommandInfo(
                                name = "AddClient",
                                privilege = Privilege.MANAGE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ClientIdentity",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                        Clusters.NetworkIdentityManagement.CommandsIncoming.RemoveClient.ID to
                            CommandInfo(
                                name = "RemoveClient",
                                privilege = Privilege.MANAGE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ClientIndex",
                                                type = DataType.CLIENT_INDEX,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "ClientIdentifier",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                        Clusters.NetworkIdentityManagement.CommandsIncoming.QueryIdentity.ID to
                            CommandInfo(
                                name = "QueryIdentity",
                                privilege = Privilege.MANAGE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "NetworkIdentityIndex",
                                                type = DataType.NETWORK_IDENTITY_INDEX,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "NetworkIdentityType",
                                                type =
                                                    DataType
                                                        .NETWORK_IDENTITY_MANAGEMENT_CLUSTER_IDENTITY_TYPE_ENUM,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "ClientIndex",
                                                type = DataType.CLIENT_INDEX,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "Identifier",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                        Clusters.NetworkIdentityManagement.CommandsIncoming.ImportAdminSecret.ID to
                            CommandInfo(
                                name = "ImportAdminSecret",
                                privilege = Privilege.ADMINISTER,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "NetworkAdministratorSharedSecret",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                        Clusters.NetworkIdentityManagement.CommandsIncoming.ExportAdminSecret.ID to
                            CommandInfo(
                                name = "ExportAdminSecret",
                                privilege = Privilege.ADMINISTER,
                                parameters = mapOf<UInt, ParameterInfo>(),
                            ),
                    ),
                commandsOutgoing =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.NetworkIdentityManagement.CommandsOutgoing.AddClientResponse.ID to
                            CommandInfo(
                                name = "AddClientResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ClientIndex",
                                                type = DataType.CLIENT_INDEX,
                                            ),
                                    ),
                            ),
                        Clusters.NetworkIdentityManagement.CommandsOutgoing.QueryIdentityResponse
                            .ID to
                            CommandInfo(
                                name = "QueryIdentityResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Identity",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                        Clusters.NetworkIdentityManagement.CommandsOutgoing
                            .ExportAdminSecretResponse
                            .ID to
                            CommandInfo(
                                name = "ExportAdminSecretResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "NetworkAdministratorSharedSecret",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                    ),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.CommissioningProxy.ID to
            ClusterInfo(
                name = "Commissioning Proxy",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.CommissioningProxy.Attributes.Transport.ID to
                            AttributeInfo(
                                name = "Transport",
                                type = DataType.CAPABILITIES_BITMAP,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.CommissioningProxy.Attributes.ScanMaxTime.ID to
                            AttributeInfo(
                                name = "ScanMaxTime",
                                type = DataType.U_INT8,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.CommissioningProxy.Attributes.MaxSessions.ID to
                            AttributeInfo(
                                name = "MaxSessions",
                                type = DataType.U_INT8,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.CommissioningProxy.Attributes.MaxCachedResults.ID to
                            AttributeInfo(
                                name = "MaxCachedResults",
                                type = DataType.U_INT8,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.CommissioningProxy.Attributes.NumCachedResults.ID to
                            AttributeInfo(
                                name = "NumCachedResults",
                                type = DataType.U_INT8,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.CommissioningProxy.Attributes.CacheTimeout.ID to
                            AttributeInfo(
                                name = "CacheTimeout",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.CommissioningProxy.Attributes.CachedResults.ID to
                            AttributeInfo(
                                name = "CachedResults",
                                type = DataType.LIST_SCAN_RESULT_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.CommissioningProxy.Attributes.WiFiBand.ID to
                            AttributeInfo(
                                name = "WiFiBand",
                                type = DataType.WI_FI_BAND_BITMAP,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.CommissioningProxy.CommandsIncoming.ProxyConnectRequest.ID to
                            CommandInfo(
                                name = "ProxyConnectRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Address",
                                                type = DataType.OCTET_STRING,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "Transport",
                                                type = DataType.CAPABILITIES_BITMAP,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "Discriminator",
                                                type = DataType.U_INT16,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "VendorID",
                                                type = DataType.VENDOR_ID,
                                            ),
                                        4u to
                                            ParameterInfo(
                                                name = "ProductID",
                                                type = DataType.U_INT16,
                                            ),
                                        5u to
                                            ParameterInfo(
                                                name = "Timeout",
                                                type = DataType.U_INT16,
                                            ),
                                        6u to
                                            ParameterInfo(
                                                name = "WiFiBand",
                                                type = DataType.WI_FI_BAND_BITMAP,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsIncoming.ProxyDisconnectRequest.ID to
                            CommandInfo(
                                name = "ProxyDisconnectRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "SessionID",
                                                type = DataType.U_INT16,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsIncoming.ProxyScanRequest.ID to
                            CommandInfo(
                                name = "ProxyScanRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Transport",
                                                type = DataType.CAPABILITIES_BITMAP,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "WiFiBands",
                                                type = DataType.WI_FI_BAND_BITMAP,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsIncoming.ProxyBackGroundScanStartRequest
                            .ID to
                            CommandInfo(
                                name = "ProxyBackGroundScanStartRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Transport",
                                                type = DataType.CAPABILITIES_BITMAP,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "Timeout",
                                                type = DataType.U_INT16,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "WiFiBands",
                                                type = DataType.WI_FI_BAND_BITMAP,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsIncoming.ProxyBackGroundScanStopRequest
                            .ID to
                            CommandInfo(
                                name = "ProxyBackGroundScanStopRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Transport",
                                                type = DataType.CAPABILITIES_BITMAP,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "WiFiBands",
                                                type = DataType.WI_FI_BAND_BITMAP,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsIncoming.ProxyMessageRequest.ID to
                            CommandInfo(
                                name = "ProxyMessageRequest",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "SessionID",
                                                type = DataType.U_INT16,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "ResponseTimeout",
                                                type = DataType.U_INT8,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "Message",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.CommissioningProxy.CommandsOutgoing.ProxyConnectResponse.ID to
                            CommandInfo(
                                name = "ProxyConnectResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "SessionID",
                                                type = DataType.U_INT16,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsOutgoing.ProxyScanResponse.ID to
                            CommandInfo(
                                name = "ProxyScanResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "NumberOfResults",
                                                type = DataType.U_INT8,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "ProxyScanResult",
                                                type = DataType.LIST_SCAN_RESULT_STRUCT,
                                            ),
                                    ),
                            ),
                        Clusters.CommissioningProxy.CommandsOutgoing.ProxyMessageResponse.ID to
                            CommandInfo(
                                name = "ProxyMessageResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "SessionID",
                                                type = DataType.U_INT16,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "Message",
                                                type = DataType.OCTET_STRING,
                                            ),
                                    ),
                            ),
                    ),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.MediaFileManagement.ID to
            ClusterInfo(
                name = "Media File Management",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.MediaFileManagement.Attributes.TotalStorage.ID to
                            AttributeInfo(
                                name = "TotalStorage",
                                type = DataType.U_INT64,
                                readPrivilege = Privilege.MANAGE,
                            ),
                        Clusters.MediaFileManagement.Attributes.AvailableStorage.ID to
                            AttributeInfo(
                                name = "AvailableStorage",
                                type = DataType.U_INT64,
                                readPrivilege = Privilege.MANAGE,
                            ),
                        Clusters.MediaFileManagement.Attributes.AvailableFiles.ID to
                            AttributeInfo(
                                name = "AvailableFiles",
                                type = DataType.LIST_FILE_DESCRIPTION_STRUCT,
                                readPrivilege = Privilege.MANAGE,
                            ),
                        Clusters.MediaFileManagement.Attributes.SupportedMimeTypes.ID to
                            AttributeInfo(
                                name = "SupportedMimeTypes",
                                type = DataType.LIST_STRING,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.MediaFileManagement.CommandsIncoming.AddFile.ID to
                            CommandInfo(
                                name = "AddFile",
                                privilege = Privilege.MANAGE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Name",
                                                type = DataType.STRING,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "Size",
                                                type = DataType.U_INT64,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "MimeType",
                                                type = DataType.STRING,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "ImageURI",
                                                type = DataType.STRING,
                                            ),
                                    ),
                            ),
                        Clusters.MediaFileManagement.CommandsIncoming.DeleteFile.ID to
                            CommandInfo(
                                name = "DeleteFile",
                                privilege = Privilege.MANAGE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "FileID",
                                                type = DataType.U_INT64,
                                            ),
                                    ),
                            ),
                        Clusters.MediaFileManagement.CommandsIncoming.RequestSharedFiles.ID to
                            CommandInfo(
                                name = "RequestSharedFiles",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ClientName",
                                                type = DataType.STRING,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "RequestID",
                                                type = DataType.U_INT16,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "SupportedMimeTypes",
                                                type = DataType.LIST_STRING,
                                            ),
                                    ),
                            ),
                        Clusters.MediaFileManagement.CommandsIncoming.GetSharedFile.ID to
                            CommandInfo(
                                name = "GetSharedFile",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ResponseID",
                                                type = DataType.U_INT16,
                                            ),
                                    ),
                            ),
                        Clusters.MediaFileManagement.CommandsIncoming.OfferFile.ID to
                            CommandInfo(
                                name = "OfferFile",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ClientName",
                                                type = DataType.STRING,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "Name",
                                                type = DataType.STRING,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "Size",
                                                type = DataType.U_INT64,
                                            ),
                                        3u to
                                            ParameterInfo(
                                                name = "MimeType",
                                                type = DataType.STRING,
                                            ),
                                        4u to
                                            ParameterInfo(
                                                name = "ImageURI",
                                                type = DataType.STRING,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.MediaFileManagement.CommandsOutgoing.AddFileResponse.ID to
                            CommandInfo(
                                name = "AddFileResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Status",
                                                type =
                                                    DataType
                                                        .MEDIA_FILE_MANAGEMENT_CLUSTER_FILE_STATUS_ENUM,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "FileID",
                                                type = DataType.U_INT64,
                                            ),
                                    ),
                            ),
                        Clusters.MediaFileManagement.CommandsOutgoing.GetSharedFileResponse.ID to
                            CommandInfo(
                                name = "GetSharedFileResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "Status",
                                                type =
                                                    DataType
                                                        .MEDIA_FILE_MANAGEMENT_CLUSTER_FILE_STATUS_ENUM,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "FileDescription",
                                                type = DataType.FILE_DESCRIPTION_STRUCT,
                                            ),
                                    ),
                            ),
                    ),
                events =
                    mapOf<EventId, EventInfo>(
                        Clusters.MediaFileManagement.Events.SharedFilesAdded.ID to
                            EventInfo(
                                name = "SharedFilesAdded",
                            ),
                    ),
            ),
        Clusters.AudioControl.ID to
            ClusterInfo(
                name = "Audio Control",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.AudioControl.Attributes.SoftMuted.ID to
                            AttributeInfo(
                                name = "SoftMuted",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.PhysicallyMuted.ID to
                            AttributeInfo(
                                name = "PhysicallyMuted",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.Volume.ID to
                            AttributeInfo(
                                name = "Volume",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.MinDeviceVolume.ID to
                            AttributeInfo(
                                name = "MinDeviceVolume",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.MaxDeviceVolume.ID to
                            AttributeInfo(
                                name = "MaxDeviceVolume",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.MaxDeviceVolumeDB.ID to
                            AttributeInfo(
                                name = "MaxDeviceVolumeDB",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.MaxUserVolume.ID to
                            AttributeInfo(
                                name = "MaxUserVolume",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.MANAGE,
                            ),
                        Clusters.AudioControl.Attributes.DefaultStepSize.ID to
                            AttributeInfo(
                                name = "DefaultStepSize",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.MANAGE,
                            ),
                        Clusters.AudioControl.Attributes.SetVolumeUnmutePolicy.ID to
                            AttributeInfo(
                                name = "SetVolumeUnmutePolicy",
                                type = DataType.AUDIO_CONTROL_CLUSTER_UNMUTE_POLICY_ENUM,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.MANAGE,
                            ),
                        Clusters.AudioControl.Attributes.IncreaseVolumeUnmutePolicy.ID to
                            AttributeInfo(
                                name = "IncreaseVolumeUnmutePolicy",
                                type = DataType.AUDIO_CONTROL_CLUSTER_UNMUTE_POLICY_ENUM,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.MANAGE,
                            ),
                        Clusters.AudioControl.Attributes.IncreaseVolumeUnmuteVolume.ID to
                            AttributeInfo(
                                name = "IncreaseVolumeUnmuteVolume",
                                type = DataType.AUDIO_CONTROL_CLUSTER_UNMUTE_VOLUME_ENUM,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.MANAGE,
                            ),
                        Clusters.AudioControl.Attributes.DecreaseVolumeUnmutePolicy.ID to
                            AttributeInfo(
                                name = "DecreaseVolumeUnmutePolicy",
                                type = DataType.AUDIO_CONTROL_CLUSTER_UNMUTE_POLICY_ENUM,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.MANAGE,
                            ),
                        Clusters.AudioControl.Attributes.StartUpMuted.ID to
                            AttributeInfo(
                                name = "StartUpMuted",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.AudioControl.Attributes.StartUpVolume.ID to
                            AttributeInfo(
                                name = "StartUpVolume",
                                type = DataType.U_INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.AudioControl.Attributes.Bass.ID to
                            AttributeInfo(
                                name = "Bass",
                                type = DataType.INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.AudioControl.Attributes.Mid.ID to
                            AttributeInfo(
                                name = "Mid",
                                type = DataType.INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.AudioControl.Attributes.Treble.ID to
                            AttributeInfo(
                                name = "Treble",
                                type = DataType.INT16,
                                readPrivilege = Privilege.VIEW,
                                writePrivilege = Privilege.OPERATE,
                            ),
                        Clusters.AudioControl.Attributes.MinCorrection.ID to
                            AttributeInfo(
                                name = "MinCorrection",
                                type = DataType.INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AudioControl.Attributes.MaxCorrection.ID to
                            AttributeInfo(
                                name = "MaxCorrection",
                                type = DataType.INT16,
                                readPrivilege = Privilege.VIEW,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.AudioControl.CommandsIncoming.Mute.ID to
                            CommandInfo(
                                name = "Mute",
                                privilege = Privilege.OPERATE,
                                parameters = mapOf<UInt, ParameterInfo>(),
                            ),
                        Clusters.AudioControl.CommandsIncoming.Unmute.ID to
                            CommandInfo(
                                name = "Unmute",
                                privilege = Privilege.OPERATE,
                                parameters = mapOf<UInt, ParameterInfo>(),
                            ),
                        Clusters.AudioControl.CommandsIncoming.ToggleMuted.ID to
                            CommandInfo(
                                name = "ToggleMuted",
                                privilege = Privilege.OPERATE,
                                parameters = mapOf<UInt, ParameterInfo>(),
                            ),
                        Clusters.AudioControl.CommandsIncoming.SetVolume.ID to
                            CommandInfo(
                                name = "SetVolume",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "NewVolume",
                                                type = DataType.U_INT16,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "UnmutePolicy",
                                                type =
                                                    DataType
                                                        .AUDIO_CONTROL_CLUSTER_UNMUTE_POLICY_ENUM,
                                            ),
                                    ),
                            ),
                        Clusters.AudioControl.CommandsIncoming.IncreaseVolume.ID to
                            CommandInfo(
                                name = "IncreaseVolume",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "StepSize",
                                                type = DataType.U_INT16,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "UnmutePolicy",
                                                type =
                                                    DataType
                                                        .AUDIO_CONTROL_CLUSTER_UNMUTE_POLICY_ENUM,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "UnmuteVolume",
                                                type =
                                                    DataType
                                                        .AUDIO_CONTROL_CLUSTER_UNMUTE_VOLUME_ENUM,
                                            ),
                                    ),
                            ),
                        Clusters.AudioControl.CommandsIncoming.DecreaseVolume.ID to
                            CommandInfo(
                                name = "DecreaseVolume",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "StepSize",
                                                type = DataType.U_INT16,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "UnmutePolicy",
                                                type =
                                                    DataType
                                                        .AUDIO_CONTROL_CLUSTER_UNMUTE_POLICY_ENUM,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing = mapOf<CommandId, CommandInfo>(),
                events = mapOf<EventId, EventInfo>(),
            ),
        Clusters.AVAnalysis.ID to
            ClusterInfo(
                name = "AV Analysis",
                attributes =
                    mapOf<AttributeId, AttributeInfo>(
                        Clusters.AVAnalysis.Attributes.SupportedAmbientContexts.ID to
                            AttributeInfo(
                                name = "SupportedAmbientContexts",
                                type = DataType.LIST_SEMANTIC_TAG_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AVAnalysis.Attributes.ActiveAmbientContextTriggers.ID to
                            AttributeInfo(
                                name = "ActiveAmbientContextTriggers",
                                type = DataType.LIST_CONTEXT_TRIGGER_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AVAnalysis.Attributes.MaxAnalysisStreamCount.ID to
                            AttributeInfo(
                                name = "MaxAnalysisStreamCount",
                                type = DataType.U_INT8,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AVAnalysis.Attributes.CurrentAnalysisStreamCount.ID to
                            AttributeInfo(
                                name = "CurrentAnalysisStreamCount",
                                type = DataType.U_INT8,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AVAnalysis.Attributes.AnalysisStreams.ID to
                            AttributeInfo(
                                name = "AnalysisStreams",
                                type = DataType.LIST_ANALYSIS_STREAM_STRUCT,
                                readPrivilege = Privilege.VIEW,
                            ),
                        Clusters.AVAnalysis.Attributes.TrackingEnabled.ID to
                            AttributeInfo(
                                name = "TrackingEnabled",
                                type = DataType.BOOLEAN,
                                readPrivilege = Privilege.MANAGE,
                                writePrivilege = Privilege.MANAGE,
                            ),
                    ),
                commandsIncoming =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.AVAnalysis.CommandsIncoming.EnableContextTriggers.ID to
                            CommandInfo(
                                name = "EnableContextTriggers",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ContextTriggers",
                                                type = DataType.LIST_CONTEXT_TRIGGER_STRUCT,
                                            ),
                                    ),
                            ),
                        Clusters.AVAnalysis.CommandsIncoming.DisableContextTriggers.ID to
                            CommandInfo(
                                name = "DisableContextTriggers",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "ContextTriggers",
                                                type = DataType.LIST_CONTEXT_TRIGGER_STRUCT,
                                            ),
                                    ),
                            ),
                        Clusters.AVAnalysis.CommandsIncoming.EstablishAnalysisStream.ID to
                            CommandInfo(
                                name = "EstablishAnalysisStream",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "NodeID",
                                                type = DataType.NODE_ID,
                                            ),
                                    ),
                            ),
                        Clusters.AVAnalysis.CommandsIncoming.ActivateAnalysisStream.ID to
                            CommandInfo(
                                name = "ActivateAnalysisStream",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "AnalysisStreamID",
                                                type = DataType.ANALYSIS_STREAM_ID,
                                            ),
                                        1u to
                                            ParameterInfo(
                                                name = "WebRTCEndpointID",
                                                type = DataType.ENDPOINT_ID,
                                            ),
                                        2u to
                                            ParameterInfo(
                                                name = "PushAVEndpointID",
                                                type = DataType.ENDPOINT_ID,
                                            ),
                                    ),
                            ),
                        Clusters.AVAnalysis.CommandsIncoming.DeactivateAnalysisStream.ID to
                            CommandInfo(
                                name = "DeactivateAnalysisStream",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "AnalysisStreamID",
                                                type = DataType.ANALYSIS_STREAM_ID,
                                            ),
                                    ),
                            ),
                        Clusters.AVAnalysis.CommandsIncoming.RemoveAnalysisStream.ID to
                            CommandInfo(
                                name = "RemoveAnalysisStream",
                                privilege = Privilege.OPERATE,
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "AnalysisStreamID",
                                                type = DataType.ANALYSIS_STREAM_ID,
                                            ),
                                    ),
                            ),
                    ),
                commandsOutgoing =
                    mapOf<CommandId, CommandInfo>(
                        Clusters.AVAnalysis.CommandsOutgoing.EstablishAnalysisStreamResponse.ID to
                            CommandInfo(
                                name = "EstablishAnalysisStreamResponse",
                                parameters =
                                    mapOf<UInt, ParameterInfo>(
                                        0u to
                                            ParameterInfo(
                                                name = "AnalysisStreamID",
                                                type = DataType.ANALYSIS_STREAM_ID,
                                            ),
                                    ),
                            ),
                    ),
                events =
                    mapOf<EventId, EventInfo>(
                        Clusters.AVAnalysis.Events.AnalysisSessionStart.ID to
                            EventInfo(
                                name = "AnalysisSessionStart",
                            ),
                        Clusters.AVAnalysis.Events.AnalysisSessionEnd.ID to
                            EventInfo(
                                name = "AnalysisSessionEnd",
                            ),
                        Clusters.AVAnalysis.Events.PerceivedContext.ID to
                            EventInfo(
                                name = "PerceivedContext",
                            ),
                    ),
            ),
    )
