// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

object Devices {
  object DoorLock {
    val ID = DeviceTypeId(0x000Au)
  }

  object DoorLockController {
    val ID = DeviceTypeId(0x000Bu)
  }

  object Aggregator {
    val ID = DeviceTypeId(0x000Eu)
  }

  object GenericSwitch {
    val ID = DeviceTypeId(0x000Fu)
  }

  object PowerSource {
    val ID = DeviceTypeId(0x0011u)
  }

  object OTARequestor {
    val ID = DeviceTypeId(0x0012u)
  }

  object BridgedNode {
    val ID = DeviceTypeId(0x0013u)
  }

  object OTAProvider {
    val ID = DeviceTypeId(0x0014u)
  }

  object ContactSensor {
    val ID = DeviceTypeId(0x0015u)
  }

  object RootNode {
    val ID = DeviceTypeId(0x0016u)
  }

  object SolarPower {
    val ID = DeviceTypeId(0x0017u)
  }

  object BatteryStorage {
    val ID = DeviceTypeId(0x0018u)
  }

  object SecondaryNetworkInterface {
    val ID = DeviceTypeId(0x0019u)
  }

  object StreamingAudioPlayer {
    val ID = DeviceTypeId(0x0020u)
  }

  object CastingAudioPlayer {
    val ID = DeviceTypeId(0x0021u)
  }

  object Speaker {
    val ID = DeviceTypeId(0x0022u)
  }

  object CastingVideoPlayer {
    val ID = DeviceTypeId(0x0023u)
  }

  object ContentApp {
    val ID = DeviceTypeId(0x0024u)
  }

  object ModeSelect {
    val ID = DeviceTypeId(0x0027u)
  }

  object BasicVideoPlayer {
    val ID = DeviceTypeId(0x0028u)
  }

  object CastingVideoClient {
    val ID = DeviceTypeId(0x0029u)
  }

  object VideoRemoteControl {
    val ID = DeviceTypeId(0x002Au)
  }

  object Fan {
    val ID = DeviceTypeId(0x002Bu)
  }

  object AirQualitySensor {
    val ID = DeviceTypeId(0x002Cu)
  }

  object AirPurifier {
    val ID = DeviceTypeId(0x002Du)
  }

  object IrrigationSystem {
    val ID = DeviceTypeId(0x0040u)
  }

  object WaterFreezeDetector {
    val ID = DeviceTypeId(0x0041u)
  }

  object WaterValve {
    val ID = DeviceTypeId(0x0042u)
  }

  object WaterLeakDetector {
    val ID = DeviceTypeId(0x0043u)
  }

  object RainSensor {
    val ID = DeviceTypeId(0x0044u)
  }

  object SoilSensor {
    val ID = DeviceTypeId(0x0045u)
  }

  object Refrigerator {
    val ID = DeviceTypeId(0x0070u)
  }

  object TemperatureControlledCabinet {
    val ID = DeviceTypeId(0x0071u)
  }

  object RoomAirConditioner {
    val ID = DeviceTypeId(0x0072u)
  }

  object LaundryWasher {
    val ID = DeviceTypeId(0x0073u)
  }

  object RoboticVacuumCleaner {
    val ID = DeviceTypeId(0x0074u)
  }

  object Dishwasher {
    val ID = DeviceTypeId(0x0075u)
  }

  object SmokeCOAlarm {
    val ID = DeviceTypeId(0x0076u)
  }

  object CookSurface {
    val ID = DeviceTypeId(0x0077u)
  }

  object Cooktop {
    val ID = DeviceTypeId(0x0078u)
  }

  object MicrowaveOven {
    val ID = DeviceTypeId(0x0079u)
  }

  object ExtractorHood {
    val ID = DeviceTypeId(0x007Au)
  }

  object Oven {
    val ID = DeviceTypeId(0x007Bu)
  }

  object LaundryDryer {
    val ID = DeviceTypeId(0x007Cu)
  }

  object HumidityConditioner {
    val ID = DeviceTypeId(0x007Du)
  }

  object NetworkInfrastructureManager {
    val ID = DeviceTypeId(0x0090u)
  }

  object ThreadBorderRouter {
    val ID = DeviceTypeId(0x0091u)
  }

  object CommissioningByProxy {
    val ID = DeviceTypeId(0x0092u)
  }

  object OnOffLight {
    val ID = DeviceTypeId(0x0100u)
  }

  object DimmableLight {
    val ID = DeviceTypeId(0x0101u)
  }

  object OnOffLightSwitch {
    val ID = DeviceTypeId(0x0103u)
  }

  object DimmerSwitch {
    val ID = DeviceTypeId(0x0104u)
  }

  object ColorDimmerSwitch {
    val ID = DeviceTypeId(0x0105u)
  }

  object LightSensor {
    val ID = DeviceTypeId(0x0106u)
  }

  object OccupancySensor {
    val ID = DeviceTypeId(0x0107u)
  }

  object OnOffPluginUnit {
    val ID = DeviceTypeId(0x010Au)
  }

  object DimmablePlugInUnit {
    val ID = DeviceTypeId(0x010Bu)
  }

  object ColorTemperatureLight {
    val ID = DeviceTypeId(0x010Cu)
  }

  object ExtendedColorLight {
    val ID = DeviceTypeId(0x010Du)
  }

  object MountedOnOffControl {
    val ID = DeviceTypeId(0x010Fu)
  }

  object MountedDimmableLoadControl {
    val ID = DeviceTypeId(0x0110u)
  }

  object JointFabricAdministrator {
    val ID = DeviceTypeId(0x0130u)
  }

  object Intercom {
    val ID = DeviceTypeId(0x0140u)
  }

  object AudioDoorbell {
    val ID = DeviceTypeId(0x0141u)
  }

  object Camera {
    val ID = DeviceTypeId(0x0142u)
  }

  object VideoDoorbell {
    val ID = DeviceTypeId(0x0143u)
  }

  object FloodlightCamera {
    val ID = DeviceTypeId(0x0144u)
  }

  object SnapshotCamera {
    val ID = DeviceTypeId(0x0145u)
  }

  object Chime {
    val ID = DeviceTypeId(0x0146u)
  }

  object CameraController {
    val ID = DeviceTypeId(0x0147u)
  }

  object Doorbell {
    val ID = DeviceTypeId(0x0148u)
  }

  object AVAnalysisNode {
    val ID = DeviceTypeId(0x0149u)
  }

  object AmbientContextSensor {
    val ID = DeviceTypeId(0x0150u)
  }

  object ProximityRanger {
    val ID = DeviceTypeId(0x0152u)
  }

  object WindowCovering {
    val ID = DeviceTypeId(0x0202u)
  }

  object WindowCoveringController {
    val ID = DeviceTypeId(0x0203u)
  }

  object Closure {
    val ID = DeviceTypeId(0x0230u)
  }

  object ClosurePanel {
    val ID = DeviceTypeId(0x0231u)
  }

  object ClosureController {
    val ID = DeviceTypeId(0x023Eu)
  }

  object HeatingCoolingUnit {
    val ID = DeviceTypeId(0x0300u)
  }

  object Thermostat {
    val ID = DeviceTypeId(0x0301u)
  }

  object TemperatureSensor {
    val ID = DeviceTypeId(0x0302u)
  }

  object Pump {
    val ID = DeviceTypeId(0x0303u)
  }

  object PumpController {
    val ID = DeviceTypeId(0x0304u)
  }

  object PressureSensor {
    val ID = DeviceTypeId(0x0305u)
  }

  object FlowSensor {
    val ID = DeviceTypeId(0x0306u)
  }

  object HumiditySensor {
    val ID = DeviceTypeId(0x0307u)
  }

  object HeatPump {
    val ID = DeviceTypeId(0x0309u)
  }

  object ThermostatController {
    val ID = DeviceTypeId(0x030Au)
  }

  object EnergyEVSE {
    val ID = DeviceTypeId(0x050Cu)
  }

  object DeviceEnergyManagement {
    val ID = DeviceTypeId(0x050Du)
  }

  object WaterHeater {
    val ID = DeviceTypeId(0x050Fu)
  }

  object ElectricalSensor {
    val ID = DeviceTypeId(0x0510u)
  }

  object ElectricalUtilityMeter {
    val ID = DeviceTypeId(0x0511u)
  }

  object MeterReferencePoint {
    val ID = DeviceTypeId(0x0512u)
  }

  object ElectricalEnergyTariff {
    val ID = DeviceTypeId(0x0513u)
  }

  object ElectricalMeter {
    val ID = DeviceTypeId(0x0514u)
  }

  object ArcFaultCircuitInterrupter {
    val ID = DeviceTypeId(0x0515u)
  }

  object ElectricalCircuitBreaker {
    val ID = DeviceTypeId(0x0516u)
  }

  object ElectricalDistributionEnclosure {
    val ID = DeviceTypeId(0x0517u)
  }

  object ElectricalSurgeProtector {
    val ID = DeviceTypeId(0x0518u)
  }

  object ResidualCurrentCircuitBreaker {
    val ID = DeviceTypeId(0x0519u)
  }

  object AuxiliaryLoadSwitch {
    val ID = DeviceTypeId(0x0520u)
  }

  object ControlBridge {
    val ID = DeviceTypeId(0x0840u)
  }

  object OnOffSensor {
    val ID = DeviceTypeId(0x0850u)
  }
}

val DEVICES =
    mapOf<DeviceTypeId, String>(
        Devices.DoorLock.ID to "Door Lock",
        Devices.DoorLockController.ID to "Door Lock Controller",
        Devices.Aggregator.ID to "Aggregator",
        Devices.GenericSwitch.ID to "Generic Switch",
        Devices.PowerSource.ID to "Power Source",
        Devices.OTARequestor.ID to "OTA Requestor",
        Devices.BridgedNode.ID to "Bridged Node",
        Devices.OTAProvider.ID to "OTA Provider",
        Devices.ContactSensor.ID to "Contact Sensor",
        Devices.RootNode.ID to "Root Node",
        Devices.SolarPower.ID to "Solar Power",
        Devices.BatteryStorage.ID to "Battery Storage",
        Devices.SecondaryNetworkInterface.ID to "Secondary Network Interface",
        Devices.StreamingAudioPlayer.ID to "Streaming Audio Player",
        Devices.CastingAudioPlayer.ID to "Casting Audio Player",
        Devices.Speaker.ID to "Speaker",
        Devices.CastingVideoPlayer.ID to "Casting Video Player",
        Devices.ContentApp.ID to "Content App",
        Devices.ModeSelect.ID to "Mode Select",
        Devices.BasicVideoPlayer.ID to "Basic Video Player",
        Devices.CastingVideoClient.ID to "Casting Video Client",
        Devices.VideoRemoteControl.ID to "Video Remote Control",
        Devices.Fan.ID to "Fan",
        Devices.AirQualitySensor.ID to "Air Quality Sensor",
        Devices.AirPurifier.ID to "Air Purifier",
        Devices.IrrigationSystem.ID to "Irrigation System",
        Devices.WaterFreezeDetector.ID to "Water Freeze Detector",
        Devices.WaterValve.ID to "Water Valve",
        Devices.WaterLeakDetector.ID to "Water Leak Detector",
        Devices.RainSensor.ID to "Rain Sensor",
        Devices.SoilSensor.ID to "Soil Sensor",
        Devices.Refrigerator.ID to "Refrigerator",
        Devices.TemperatureControlledCabinet.ID to "Temperature Controlled Cabinet",
        Devices.RoomAirConditioner.ID to "Room Air Conditioner",
        Devices.LaundryWasher.ID to "Laundry Washer",
        Devices.RoboticVacuumCleaner.ID to "Robotic Vacuum Cleaner",
        Devices.Dishwasher.ID to "Dishwasher",
        Devices.SmokeCOAlarm.ID to "Smoke CO Alarm",
        Devices.CookSurface.ID to "Cook Surface",
        Devices.Cooktop.ID to "Cooktop",
        Devices.MicrowaveOven.ID to "Microwave Oven",
        Devices.ExtractorHood.ID to "Extractor Hood",
        Devices.Oven.ID to "Oven",
        Devices.LaundryDryer.ID to "Laundry Dryer",
        Devices.HumidityConditioner.ID to "Humidity Conditioner",
        Devices.NetworkInfrastructureManager.ID to "Network Infrastructure Manager",
        Devices.ThreadBorderRouter.ID to "Thread Border Router",
        Devices.CommissioningByProxy.ID to "Commissioning By Proxy",
        Devices.OnOffLight.ID to "On/Off Light",
        Devices.DimmableLight.ID to "Dimmable Light",
        Devices.OnOffLightSwitch.ID to "On/Off Light Switch",
        Devices.DimmerSwitch.ID to "Dimmer Switch",
        Devices.ColorDimmerSwitch.ID to "Color Dimmer Switch",
        Devices.LightSensor.ID to "Light Sensor",
        Devices.OccupancySensor.ID to "Occupancy Sensor",
        Devices.OnOffPluginUnit.ID to "On/Off Plug-in Unit",
        Devices.DimmablePlugInUnit.ID to "Dimmable Plug-In Unit",
        Devices.ColorTemperatureLight.ID to "Color Temperature Light",
        Devices.ExtendedColorLight.ID to "Extended Color Light",
        Devices.MountedOnOffControl.ID to "Mounted On/Off Control",
        Devices.MountedDimmableLoadControl.ID to "Mounted Dimmable Load Control",
        Devices.JointFabricAdministrator.ID to "Joint Fabric Administrator",
        Devices.Intercom.ID to "Intercom",
        Devices.AudioDoorbell.ID to "Audio Doorbell",
        Devices.Camera.ID to "Camera",
        Devices.VideoDoorbell.ID to "Video Doorbell",
        Devices.FloodlightCamera.ID to "Floodlight Camera",
        Devices.SnapshotCamera.ID to "Snapshot Camera",
        Devices.Chime.ID to "Chime",
        Devices.CameraController.ID to "Camera Controller",
        Devices.Doorbell.ID to "Doorbell",
        Devices.AVAnalysisNode.ID to "AV Analysis Node",
        Devices.AmbientContextSensor.ID to "Ambient Context Sensor",
        Devices.ProximityRanger.ID to "Proximity Ranger",
        Devices.WindowCovering.ID to "Window Covering",
        Devices.WindowCoveringController.ID to "Window Covering Controller",
        Devices.Closure.ID to "Closure",
        Devices.ClosurePanel.ID to "Closure Panel",
        Devices.ClosureController.ID to "Closure Controller",
        Devices.HeatingCoolingUnit.ID to "Heating/Cooling Unit",
        Devices.Thermostat.ID to "Thermostat",
        Devices.TemperatureSensor.ID to "Temperature Sensor",
        Devices.Pump.ID to "Pump",
        Devices.PumpController.ID to "Pump Controller",
        Devices.PressureSensor.ID to "Pressure Sensor",
        Devices.FlowSensor.ID to "Flow Sensor",
        Devices.HumiditySensor.ID to "Humidity Sensor",
        Devices.HeatPump.ID to "Heat Pump",
        Devices.ThermostatController.ID to "Thermostat Controller",
        Devices.EnergyEVSE.ID to "Energy EVSE",
        Devices.DeviceEnergyManagement.ID to "Device Energy Management",
        Devices.WaterHeater.ID to "Water Heater",
        Devices.ElectricalSensor.ID to "Electrical Sensor",
        Devices.ElectricalUtilityMeter.ID to "Electrical Utility Meter",
        Devices.MeterReferencePoint.ID to "Meter Reference Point",
        Devices.ElectricalEnergyTariff.ID to "Electrical Energy Tariff",
        Devices.ElectricalMeter.ID to "Electrical Meter",
        Devices.ArcFaultCircuitInterrupter.ID to "Arc Fault Circuit Interrupter",
        Devices.ElectricalCircuitBreaker.ID to "Electrical Circuit Breaker",
        Devices.ElectricalDistributionEnclosure.ID to "Electrical Distribution Enclosure",
        Devices.ElectricalSurgeProtector.ID to "Electrical Surge Protector",
        Devices.ResidualCurrentCircuitBreaker.ID to "Residual Current Circuit Breaker",
        Devices.AuxiliaryLoadSwitch.ID to "Auxiliary Load Switch",
        Devices.ControlBridge.ID to "Control Bridge",
        Devices.OnOffSensor.ID to "On/Off Sensor",
    )
