// SPDX-FileCopyrightText: 2026 The Authors
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by matter-data-model-parser.py - do not edit.

package io.aether.android.matter

object Enums {
  enum class ACLClusterAccessControlAuxiliaryType(val value: Int) {
    System(0),
    Groupcast(1),
  }

  enum class ACLClusterAccessControlEntryAuthMode(val value: Int) {
    PASE(1),
    CASE(2),
    Group(3),
  }

  enum class ACLClusterAccessControlEntryPrivilege(val value: Int) {
    View(1),
    ProxyView(2),
    Operate(3),
    Manage(4),
    Administer(5),
  }

  enum class ACLClusterAccessRestrictionType(val value: Int) {
    AttributeAccessForbidden(0),
    AttributeWriteForbidden(1),
    CommandForbidden(2),
    EventForbidden(3),
  }

  enum class ACLClusterChangeType(val value: Int) {
    Changed(0),
    Added(1),
    Removed(2),
  }

  enum class AVAnalysisClusterAnalysisStreamState(val value: Int) {
    PendingInitiation(0),
    Failure(1),
    WebRTCInitiated(2),
    PushAVAllocated(3),
    WebRTCActive(4),
    PushAVActive(5),
    PushAVPendingDeactivation(6),
    WebRTCPendingDeactivation(7),
  }

  enum class ActionsClusterActionError(val value: Int) {
    Unknown(0),
    Interrupted(1),
  }

  enum class ActionsClusterActionState(val value: Int) {
    Inactive(0),
    Active(1),
    Paused(2),
    Disabled(3),
  }

  enum class ActionsClusterActionType(val value: Int) {
    Other(0),
    Scene(1),
    Sequence(2),
    Automation(3),
    Exception(4),
    Notification(5),
    Alarm(6),
  }

  enum class ActionsClusterEndpointListType(val value: Int) {
    Other(0),
    Room(1),
    Zone(2),
  }

  enum class AdminCommissioningClusterCommissioningWindowStatus(val value: Int) {
    WindowNotOpen(0),
    EnhancedWindowOpen(1),
    BasicWindowOpen(2),
  }

  enum class AdminCommissioningClusterStatusCode(val value: Int) {
    Busy(2),
    PAKEParameterError(3),
    WindowNotOpen(4),
  }

  enum class AirQualityClusterAirQuality(val value: Int) {
    Unknown(0),
    Good(1),
    Fair(2),
    Moderate(3),
    Poor(4),
    VeryPoor(5),
    ExtremelyPoor(6),
  }

  enum class AmbientSensingUnionClusterUnionContributorStatus(val value: Int) {
    UnionContributorOnline(0),
    UnionContributorOffline(1),
  }

  enum class AmbientSensingUnionClusterUnionHealth(val value: Int) {
    FullyFunctional(0),
    LimitedDegraded(1),
    NonFunctional(2),
  }

  enum class ApplicationBasicClusterApplicationStatus(val value: Int) {
    Stopped(0),
    ActiveVisibleFocus(1),
    ActiveHidden(2),
    ActiveVisibleNotFocus(3),
  }

  enum class ApplicationLauncherClusterStatus(val value: Int) {
    Success(0),
    AppNotAvailable(1),
    SystemBusy(2),
    PendingUserApproval(3),
    Downloading(4),
    Installing(5),
  }

  enum class AudioControlClusterUnmutePolicy(val value: Int) {
    UnmuteOrChangeVolume(0),
    UnmuteOrDoNotChangeVolume(1),
    DoNotUnmuteAndChangeVolume(2),
    DoNotUnmuteAndDoNotChangeVolume(3),
  }

  enum class AudioControlClusterUnmuteVolume(val value: Int) {
    MinDeviceVolume(0),
    Volume(1),
    VolumePlusStepSize(2),
  }

  enum class AudioOutputClusterOutputType(val value: Int) {
    HDMI(0),
    BT(1),
    Optical(2),
    Headphone(3),
    Internal(4),
    Other(5),
  }

  enum class BasicInformationClusterColor(val value: Int) {
    Black(0),
    Navy(1),
    Green(2),
    Teal(3),
    Maroon(4),
    Purple(5),
    Olive(6),
    Gray(7),
    Blue(8),
    Lime(9),
    Aqua(10),
    Red(11),
    Fuchsia(12),
    Yellow(13),
    White(14),
    Nickel(15),
    Chrome(16),
    Brass(17),
    Copper(18),
    Silver(19),
    Gold(20),
  }

  enum class BasicInformationClusterProductFinish(val value: Int) {
    Other(0),
    Matte(1),
    Satin(2),
    Polished(3),
    Rugged(4),
    Fabric(5),
  }

  enum class BridgedDeviceBasicInformationClusterColor(val value: Int) {
    Black(0),
    Navy(1),
    Green(2),
    Teal(3),
    Maroon(4),
    Purple(5),
    Olive(6),
    Gray(7),
    Blue(8),
    Lime(9),
    Aqua(10),
    Red(11),
    Fuchsia(12),
    Yellow(13),
    White(14),
    Nickel(15),
    Chrome(16),
    Brass(17),
    Copper(18),
    Silver(19),
    Gold(20),
  }

  enum class BridgedDeviceBasicInformationClusterProductFinish(val value: Int) {
    Other(0),
    Matte(1),
    Satin(2),
    Polished(3),
    Rugged(4),
    Fabric(5),
  }

  enum class CameraAVSettingsUserLevelManagementClusterPhysicalMovement(val value: Int) {
    Idle(0),
    Moving(1),
  }

  enum class CameraAVStreamManagementClusterAudioCodec(val value: Int) {
    OPUS(0),
    AACLC(1),
  }

  enum class CameraAVStreamManagementClusterImageCodec(val value: Int) {
    JPEG(0),
    HEIC(1),
  }

  enum class CameraAVStreamManagementClusterTriStateAuto(val value: Int) {
    Off(0),
    On(1),
    Auto(2),
  }

  enum class CameraAVStreamManagementClusterTwoWayTalkSupportType(val value: Int) {
    NotSupported(0),
    HalfDuplex(1),
    FullDuplex(2),
  }

  enum class CameraAVStreamManagementClusterVideoCodec(val value: Int) {
    H264(0),
    HEVC(1),
    VVC(2),
    AV1(3),
  }

  enum class ChannelClusterChannelType(val value: Int) {
    Satellite(0),
    Cable(1),
    Terrestrial(2),
    OTT(3),
  }

  enum class ChannelClusterLineupInfoType(val value: Int) {
    MSO(0),
  }

  enum class ChannelClusterStatus(val value: Int) {
    Success(0),
    MultipleMatches(1),
    NoMatches(2),
  }

  enum class ClosureControlClusterClosureError(val value: Int) {
    PhysicallyBlocked(0),
    BlockedBySensor(1),
    TemperatureLimited(2),
    MaintenanceRequired(3),
    InternalInterference(4),
  }

  enum class ClosureControlClusterCurrentPosition(val value: Int) {
    FullyClosed(0),
    FullyOpened(1),
    PartiallyOpened(2),
    OpenedForPedestrian(3),
    OpenedForVentilation(4),
    OpenedAtSignature(5),
  }

  enum class ClosureControlClusterMainState(val value: Int) {
    Stopped(0),
    Moving(1),
    WaitingForMotion(2),
    Error(3),
    Calibrating(4),
    Protected(5),
    Disengaged(6),
    SetupRequired(7),
  }

  enum class ClosureControlClusterTargetPosition(val value: Int) {
    MoveToFullyClosed(0),
    MoveToFullyOpen(1),
    MoveToPedestrianPosition(2),
    MoveToVentilationPosition(3),
    MoveToSignaturePosition(4),
  }

  enum class ClosureDimensionClusterClosureUnit(val value: Int) {
    Millimeter(0),
    Degree(1),
  }

  enum class ClosureDimensionClusterModulationType(val value: Int) {
    SlatsOrientation(0),
    SlatsOpenwork(1),
    StripesAlignment(2),
    Opacity(3),
    Ventilation(4),
  }

  enum class ClosureDimensionClusterOverflow(val value: Int) {
    NoOverflow(0),
    Inside(1),
    Outside(2),
    TopInside(3),
    TopOutside(4),
    BottomInside(5),
    BottomOutside(6),
    LeftInside(7),
    LeftOutside(8),
    RightInside(9),
    RightOutside(10),
  }

  enum class ClosureDimensionClusterRotationAxis(val value: Int) {
    Left(0),
    CenteredVertical(1),
    LeftAndRight(2),
    Right(3),
    Top(4),
    CenteredHorizontal(5),
    TopAndBottom(6),
    Bottom(7),
    LeftBarrier(8),
    LeftAndRightBarriers(9),
    RightBarrier(10),
  }

  enum class ClosureDimensionClusterStepDirection(val value: Int) {
    Decrease(0),
    Increase(1),
  }

  enum class ClosureDimensionClusterTranslationDirection(val value: Int) {
    Downward(0),
    Upward(1),
    VerticalMask(2),
    VerticalSymmetry(3),
    Leftward(4),
    Rightward(5),
    HorizontalMask(6),
    HorizontalSymmetry(7),
    Forward(8),
    Backward(9),
    DepthMask(10),
    DepthSymmetry(11),
  }

  enum class ColorControlClusterColorLoopAction(val value: Int) {
    Deactivate(0),
    ActivateFromColorLoopStartEnhancedHue(1),
    ActivateFromEnhancedCurrentHue(2),
  }

  enum class ColorControlClusterColorLoopDirection(val value: Int) {
    Decrement(0),
    Increment(1),
  }

  enum class ColorControlClusterColorMode(val value: Int) {
    CurrentHueAndCurrentSaturation(0),
    CurrentXAndCurrentY(1),
    ColorTemperatureMireds(2),
  }

  enum class ColorControlClusterDirection(val value: Int) {
    Shortest(0),
    Longest(1),
    Up(2),
    Down(3),
  }

  enum class ColorControlClusterDriftCompensation(val value: Int) {
    None(0),
    OtherOrUnknown(1),
    TemperatureMonitoring(2),
    OpticalLuminanceMonitoringAndFeedback(3),
    OpticalColorMonitoringAndFeedback(4),
  }

  enum class ColorControlClusterEnhancedColorMode(val value: Int) {
    CurrentHueAndCurrentSaturation(0),
    CurrentXAndCurrentY(1),
    ColorTemperatureMireds(2),
    EnhancedCurrentHueAndCurrentSaturation(3),
  }

  enum class ColorControlClusterMoveMode(val value: Int) {
    Stop(0),
    Up(1),
    Down(3),
  }

  enum class ColorControlClusterStepMode(val value: Int) {
    Up(1),
    Down(3),
  }

  enum class CommodityTariffClusterAuxiliaryLoadSetting(val value: Int) {
    Off(0),
    On(1),
    None(2),
  }

  enum class CommodityTariffClusterBlockMode(val value: Int) {
    NoBlock(0),
    Combined(1),
    Individual(2),
  }

  enum class CommodityTariffClusterDayEntryRandomizationType(val value: Int) {
    None(0),
    Fixed(1),
    Random(2),
    RandomPositive(3),
    RandomNegative(4),
  }

  enum class CommodityTariffClusterDayType(val value: Int) {
    Standard(0),
    Holiday(1),
    Dynamic(2),
    Event(3),
  }

  enum class CommodityTariffClusterPeakPeriodSeverity(val value: Int) {
    Unused(0),
    Low(1),
    Medium(2),
    High(3),
  }

  enum class ConcentrationMeasurementClusterLevelValue(val value: Int) {
    Unknown(0),
    Low(1),
    Medium(2),
    High(3),
    Critical(4),
  }

  enum class ConcentrationMeasurementClusterMeasurementMedium(val value: Int) {
    Air(0),
    Water(1),
    Soil(2),
  }

  enum class ConcentrationMeasurementClusterMeasurementUnit(val value: Int) {
    PPM(0),
    PPB(1),
    PPT(2),
    MGM3(3),
    UGM3(4),
    NGM3(5),
    PM3(6),
    BQM3(7),
    DBPM(8),
    PCFT(9),
  }

  enum class ContentAppObserverClusterStatus(val value: Int) {
    Success(0),
    UnexpectedData(1),
  }

  enum class ContentControlClusterStatusCode(val value: Int) {
    InvalidPINCode(2),
    InvalidRating(3),
    InvalidChannel(4),
    ChannelAlreadyExist(5),
    ChannelNotExist(6),
    UnidentifiableApplication(7),
    ApplicationAlreadyExist(8),
    ApplicationNotExist(9),
    TimeWindowAlreadyExist(10),
    TimeWindowNotExist(11),
  }

  enum class ContentLauncherClusterMetricType(val value: Int) {
    Pixels(0),
    Percentage(1),
  }

  enum class ContentLauncherClusterParameter(val value: Int) {
    Actor(0),
    Channel(1),
    Character(2),
    Director(3),
    Event(4),
    Franchise(5),
    Genre(6),
    League(7),
    Popularity(8),
    Provider(9),
    Sport(10),
    SportsTeam(11),
    Type(12),
    Video(13),
    Season(14),
    Episode(15),
    Any(16),
  }

  enum class ContentLauncherClusterQueueType(val value: Int) {
    Replace(0),
    Next(1),
    Last(2),
  }

  enum class ContentLauncherClusterStatus(val value: Int) {
    Success(0),
    URLNotAvailable(1),
    AuthFailed(2),
    TextTrackNotAvailable(3),
    AudioTrackNotAvailable(4),
    InvalidData(5),
    AccountMismatch(6),
    ContentAppNotAvailable(7),
    ReplicationNotAllowed(8),
    ReplicationNotSupported(9),
    PresetNotFound(10),
  }

  enum class DeviceEnergyManagementClusterAdjustmentCause(val value: Int) {
    LocalOptimization(0),
    GridOptimization(1),
  }

  enum class DeviceEnergyManagementClusterCause(val value: Int) {
    NormalCompletion(0),
    Offline(1),
    Fault(2),
    UserOptOut(3),
    Cancelled(4),
    Invalid(5),
  }

  enum class DeviceEnergyManagementClusterCostType(val value: Int) {
    Financial(0),
    GHGEmissions(1),
    Comfort(2),
    Temperature(3),
  }

  enum class DeviceEnergyManagementClusterESAState(val value: Int) {
    Offline(0),
    Online(1),
    Fault(2),
    PowerAdjustActive(3),
    Paused(4),
  }

  enum class DeviceEnergyManagementClusterESAType(val value: Int) {
    EVSE(0),
    SpaceHeating(1),
    WaterHeating(2),
    SpaceCooling(3),
    SpaceHeatingCooling(4),
    BatteryStorage(5),
    SolarPV(6),
    FridgeFreezer(7),
    WashingMachine(8),
    Dishwasher(9),
    Cooking(10),
    HomeWaterPump(11),
    IrrigationWaterPump(12),
    PoolPump(13),
    Other(255),
  }

  enum class DeviceEnergyManagementClusterForecastUpdateReason(val value: Int) {
    InternalOptimization(0),
    LocalOptimization(1),
    GridOptimization(2),
  }

  enum class DeviceEnergyManagementClusterOptOutState(val value: Int) {
    NoOptOut(0),
    LocalOptOut(1),
    GridOptOut(2),
    OptOut(3),
  }

  enum class DeviceEnergyManagementClusterPowerAdjustReason(val value: Int) {
    NoAdjustment(0),
    LocalOptimizationAdjustment(1),
    GridOptimizationAdjustment(2),
  }

  enum class DiagnosticLogsClusterIntent(val value: Int) {
    EndUserSupport(0),
    NetworkDiag(1),
    CrashLogs(2),
  }

  enum class DiagnosticLogsClusterStatus(val value: Int) {
    Success(0),
    Exhausted(1),
    NoLogs(2),
    Busy(3),
    Denied(4),
  }

  enum class DiagnosticLogsClusterTransferProtocol(val value: Int) {
    ResponsePayload(0),
    BDX(1),
  }

  enum class DiagnosticsEthernetClusterPHYRate(val value: Int) {
    Rate10M(0),
    Rate100M(1),
    Rate1G(2),
    Rate2_5G(3),
    Rate5G(4),
    Rate10G(5),
    Rate40G(6),
    Rate100G(7),
    Rate200G(8),
    Rate400G(9),
  }

  enum class DiagnosticsGeneralClusterBootReason(val value: Int) {
    Unspecified(0),
    PowerOnReboot(1),
    BrownOutReset(2),
    SoftwareWatchdogReset(3),
    HardwareWatchdogReset(4),
    SoftwareUpdateCompleted(5),
    SoftwareReset(6),
  }

  enum class DiagnosticsGeneralClusterHardwareFault(val value: Int) {
    Unspecified(0),
    Radio(1),
    Sensor(2),
    ResettableOverTemp(3),
    NonResettableOverTemp(4),
    PowerSource(5),
    VisualDisplayFault(6),
    AudioOutputFault(7),
    UserInterfaceFault(8),
    NonVolatileMemoryError(9),
    TamperDetected(10),
  }

  enum class DiagnosticsGeneralClusterInterfaceType(val value: Int) {
    Unspecified(0),
    WiFi(1),
    Ethernet(2),
    Cellular(3),
    Thread(4),
  }

  enum class DiagnosticsGeneralClusterNetworkFault(val value: Int) {
    Unspecified(0),
    HardwareFailure(1),
    NetworkJammed(2),
    ConnectionFailed(3),
  }

  enum class DiagnosticsGeneralClusterRadioFault(val value: Int) {
    Unspecified(0),
    WiFiFault(1),
    CellularFault(2),
    ThreadFault(3),
    NFCFault(4),
    BLEFault(5),
    EthernetFault(6),
  }

  enum class DiagnosticsThreadClusterConnectionStatus(val value: Int) {
    Connected(0),
    NotConnected(1),
  }

  enum class DiagnosticsThreadClusterNetworkFault(val value: Int) {
    Unspecified(0),
    LinkDown(1),
    HardwareFailure(2),
    NetworkJammed(3),
  }

  enum class DiagnosticsThreadClusterRoutingRole(val value: Int) {
    Unspecified(0),
    Unassigned(1),
    SleepyEndDevice(2),
    EndDevice(3),
    REED(4),
    Router(5),
    Leader(6),
  }

  enum class DiagnosticsWiFiClusterAssociationFailureCause(val value: Int) {
    Unknown(0),
    AssociationFailed(1),
    AuthenticationFailed(2),
    SsidNotFound(3),
  }

  enum class DiagnosticsWiFiClusterConnectionStatus(val value: Int) {
    Connected(0),
    NotConnected(1),
  }

  enum class DiagnosticsWiFiClusterSecurityType(val value: Int) {
    Unspecified(0),
    None(1),
    WEP(2),
    WPA(3),
    WPA2(4),
    WPA3(5),
  }

  enum class DiagnosticsWiFiClusterWiFiVersion(val value: Int) {
    A(0),
    B(1),
    G(2),
    N(3),
    Ac(4),
    Ax(5),
    Ah(6),
  }

  enum class DoorLockClusterAlarmCode(val value: Int) {
    LockJammed(0),
    LockFactoryReset(1),
    LockRadioPowerCycled(3),
    WrongCodeEntryLimit(4),
    FrontEsceutcheonRemoved(5),
    DoorForcedOpen(6),
    DoorAjar(7),
    ForcedUser(8),
  }

  enum class DoorLockClusterCredentialRule(val value: Int) {
    Single(0),
    Dual(1),
    Tri(2),
  }

  enum class DoorLockClusterCredentialType(val value: Int) {
    ProgrammingPIN(0),
    PIN(1),
    RFID(2),
    Fingerprint(3),
    FingerVein(4),
    Face(5),
    AliroCredentialIssuerKey(6),
    AliroEvictableEndpointKey(7),
    AliroNonEvictableEndpointKey(8),
  }

  enum class DoorLockClusterDataOperationType(val value: Int) {
    Add(0),
    Clear(1),
    Modify(2),
  }

  enum class DoorLockClusterDoorState(val value: Int) {
    DoorOpen(0),
    DoorClosed(1),
    DoorJammed(2),
    DoorForcedOpen(3),
    DoorUnspecifiedError(4),
    DoorAjar(5),
  }

  enum class DoorLockClusterEventType(val value: Int) {
    Operation(0),
    Programming(1),
    Alarm(2),
  }

  enum class DoorLockClusterLEDSetting(val value: Int) {
    NoLEDSignal(0),
    NoLEDSignalAccessAllowed(1),
    LEDSignalAll(2),
  }

  enum class DoorLockClusterLockDataType(val value: Int) {
    Unspecified(0),
    ProgrammingCode(1),
    UserIndex(2),
    WeekDaySchedule(3),
    YearDaySchedule(4),
    HolidaySchedule(5),
    PIN(6),
    RFID(7),
    Fingerprint(8),
    FingerVein(9),
    Face(10),
    AliroCredentialIssuerKey(11),
    AliroEvictableEndpointKey(12),
    AliroNonEvictableEndpointKey(13),
  }

  enum class DoorLockClusterLockOperationType(val value: Int) {
    Lock(0),
    Unlock(1),
    NonAccessUserEvent(2),
    ForcedUserEvent(3),
    Unlatch(4),
  }

  enum class DoorLockClusterLockState(val value: Int) {
    NotFullyLocked(0),
    Locked(1),
    Unlocked(2),
    Unlatched(3),
  }

  enum class DoorLockClusterLockType(val value: Int) {
    DeadBolt(0),
    Magnetic(1),
    Other(2),
    Mortise(3),
    Rim(4),
    LatchBolt(5),
    CylindricalLock(6),
    TubularLock(7),
    InterconnectedLock(8),
    DeadLatch(9),
    DoorFurniture(10),
    Eurocylinder(11),
  }

  enum class DoorLockClusterOperatingMode(val value: Int) {
    Normal(0),
    Vacation(1),
    Privacy(2),
    NoRemoteLockUnlock(3),
    Passage(4),
  }

  enum class DoorLockClusterOperationError(val value: Int) {
    Unspecified(0),
    InvalidCredential(1),
    DisabledUserDenied(2),
    Restricted(3),
    InsufficientBattery(4),
  }

  enum class DoorLockClusterOperationSource(val value: Int) {
    Unspecified(0),
    Manual(1),
    ProprietaryRemote(2),
    Keypad(3),
    Auto(4),
    Button(5),
    Schedule(6),
    Remote(7),
    RFID(8),
    Biometric(9),
    Aliro(10),
  }

  enum class DoorLockClusterSoundVolume(val value: Int) {
    Silent(0),
    Low(1),
    High(2),
    Medium(3),
  }

  enum class DoorLockClusterStatusCode(val value: Int) {
    Duplicate(2),
    Occupied(3),
  }

  enum class DoorLockClusterUserStatus(val value: Int) {
    Available(0),
    OccupiedEnabled(1),
    OccupiedDisabled(3),
  }

  enum class DoorLockClusterUserType(val value: Int) {
    UnrestrictedUser(0),
    YearDayScheduleUser(1),
    WeekDayScheduleUser(2),
    ProgrammingUser(3),
    NonAccessUser(4),
    ForcedUser(5),
    DisposableUser(6),
    ExpiringUser(7),
    ScheduleRestrictedUser(8),
    RemoteOnlyUser(9),
  }

  enum class ElectricalDistributionClusterEndOfLife(val value: Int) {
    None(0),
    Damaged(1),
    Degraded(2),
    Expired(3),
  }

  enum class ElectricalEnergyMeasurementClusterMeasurementType(val value: Int) {
    Unspecified(0),
    Voltage(1),
    ActiveCurrent(2),
    ReactiveCurrent(3),
    ApparentCurrent(4),
    ActivePower(5),
    ReactivePower(6),
    ApparentPower(7),
    RMSVoltage(8),
    RMSCurrent(9),
    RMSPower(10),
    Frequency(11),
    PowerFactor(12),
    NeutralCurrent(13),
    ElectricalEnergy(14),
    ReactiveEnergy(15),
    ApparentEnergy(16),
  }

  enum class ElectricalGridConditionsClusterThreeLevel(val value: Int) {
    Low(0),
    Medium(1),
    High(2),
  }

  enum class ElectricalPowerMeasurementClusterMeasurementType(val value: Int) {
    Unspecified(0),
    Voltage(1),
    ActiveCurrent(2),
    ReactiveCurrent(3),
    ApparentCurrent(4),
    ActivePower(5),
    ReactivePower(6),
    ApparentPower(7),
    RMSVoltage(8),
    RMSCurrent(9),
    RMSPower(10),
    Frequency(11),
    PowerFactor(12),
    NeutralCurrent(13),
    ElectricalEnergy(14),
    ReactiveEnergy(15),
    ApparentEnergy(16),
  }

  enum class ElectricalPowerMeasurementClusterPowerMode(val value: Int) {
    Unknown(0),
    DC(1),
    AC(2),
  }

  enum class ElectricalProtectionAlarmClusterCurrentTripCurve(val value: Int) {
    TypeZ(0),
    TypeB(1),
    TypeC(2),
    TypeK(3),
    TypeD(4),
  }

  enum class ElectricalProtectionAlarmClusterCurrentWaveform(val value: Int) {
    AC(0),
    A(1),
    F(2),
    B(3),
  }

  enum class ElectricalProtectionAlarmClusterGroundFaultClass(val value: Int) {
    ClassA(0),
    ClassB(1),
    ClassC(2),
    ClassD(3),
    ClassE(4),
  }

  enum class ElectricalProtectionAlarmClusterUtilizationCategory(val value: Int) {
    CategoryA(0),
    CategoryB(1),
  }

  enum class EnergyEVSEClusterEnergyTransferStoppedReason(val value: Int) {
    EVStopped(0),
    EVSEStopped(1),
    Other(2),
  }

  enum class EnergyEVSEClusterFaultState(val value: Int) {
    NoError(0),
    MeterFailure(1),
    OverVoltage(2),
    UnderVoltage(3),
    OverCurrent(4),
    ContactWetFailure(5),
    ContactDryFailure(6),
    GroundFault(7),
    PowerLoss(8),
    PowerQuality(9),
    PilotShortCircuit(10),
    EmergencyStop(11),
    EVDisconnected(12),
    WrongPowerSupply(13),
    LiveNeutralSwap(14),
    OverTemperature(15),
    Other(255),
  }

  enum class EnergyEVSEClusterState(val value: Int) {
    NotPluggedIn(0),
    PluggedInNoDemand(1),
    PluggedInDemand(2),
    PluggedInCharging(3),
    PluggedInDischarging(4),
    SessionEnding(5),
    Fault(6),
  }

  enum class EnergyEVSEClusterSupplyState(val value: Int) {
    Disabled(0),
    ChargingEnabled(1),
    DischargingEnabled(2),
    DisabledError(3),
    DisabledDiagnostics(4),
    Enabled(5),
  }

  enum class EnergyPreferenceClusterEnergyPriority(val value: Int) {
    Comfort(0),
    Speed(1),
    Efficiency(2),
    WaterConsumption(3),
  }

  enum class FanControlClusterAirflowDirection(val value: Int) {
    Forward(0),
    Reverse(1),
  }

  enum class FanControlClusterFanMode(val value: Int) {
    Off(0),
    Low(1),
    Medium(2),
    High(3),
    On(4),
    Auto(5),
    Smart(6),
  }

  enum class FanControlClusterFanModeSequence(val value: Int) {
    OffLowMedHigh(0),
    OffLowHigh(1),
    OffLowMedHighAuto(2),
    OffLowHighAuto(3),
    OffHighAuto(4),
    OffHigh(5),
  }

  enum class FanControlClusterStepDirection(val value: Int) {
    Increase(0),
    Decrease(1),
  }

  enum class GeneralCommissioningClusterCommissioningError(val value: Int) {
    OK(0),
    ValueOutsideRange(1),
    InvalidAuthentication(2),
    NoFailSafe(3),
    BusyWithOtherAdmin(4),
    RequiredTCNotAccepted(5),
    TCAcknowledgementsNotReceived(6),
    TCMinVersionNotMet(7),
  }

  enum class GeneralCommissioningClusterNetworkRecoveryReason(val value: Int) {
    Unspecified(0),
    Auth(1),
    Visibility(2),
  }

  enum class GeneralCommissioningClusterRegulatoryLocationType(val value: Int) {
    Indoor(0),
    Outdoor(1),
    IndoorOutdoor(2),
  }

  enum class GroupKeyManagementClusterGroupKeyMulticastPolicy(val value: Int) {
    PerGroupID(0),
    AllNodes(1),
  }

  enum class GroupKeyManagementClusterGroupKeySecurityPolicy(val value: Int) {
    TrustFirst(0),
    CacheAndSync(1),
  }

  enum class GroupcastClusterGroupcastTestResult(val value: Int) {
    Success(0),
    GeneralError(1),
    MessageReplay(2),
    FailedAuth(3),
    NoAvailableKey(4),
    SendFailure(5),
    UnknownGroup(6),
  }

  enum class GroupcastClusterGroupcastTesting(val value: Int) {
    DisableTesting(0),
    EnableListenerTesting(1),
    EnableSenderTesting(2),
  }

  enum class GroupcastClusterMulticastAddrPolicy(val value: Int) {
    IanaAddr(0),
    PerGroup(1),
  }

  enum class HumidistatClusterMode(val value: Int) {
    Humidifier(0),
    Dehumidifier(1),
    Auto(2),
    FanOnly(3),
  }

  enum class HumidistatClusterSystemState(val value: Int) {
    Humidifying(0),
    Dehumidifying(1),
    Fan(2),
    Idle(3),
  }

  enum class ICDManagementClusterClientType(val value: Int) {
    Permanent(0),
    Ephemeral(1),
  }

  enum class ICDManagementClusterOperatingMode(val value: Int) {
    SIT(0),
    LIT(1),
  }

  enum class IdentifyClusterEffectIdentifier(val value: Int) {
    Blink(0),
    Breathe(1),
    Okay(2),
    ChannelChange(11),
    FinishEffect(254),
    StopEffect(255),
  }

  enum class IdentifyClusterEffectVariant(val value: Int) {
    Default(0),
  }

  enum class IdentifyClusterIdentifyType(val value: Int) {
    None(0),
    LightOutput(1),
    VisibleIndicator(2),
    AudibleBeep(3),
    Display(4),
    Actuator(5),
  }

  enum class IlluminanceMeasurementClusterLightSensorType(val value: Int) {
    Photodiode(0),
    CMOS(1),
  }

  enum class JointFabricAdministratorClusterICACCSRResponseStatusCode(val value: Int) {
    OK(0),
    Busy(1),
    PAKEParameterError(2),
    WindowNotOpen(3),
    VIDNotVerified(4),
    InvalidAdministratorFabricIndex(5),
  }

  enum class JointFabricAdministratorClusterICACResponseStatus(val value: Int) {
    OK(0),
    InvalidPublicKey(1),
    InvalidICAC(2),
  }

  enum class JointFabricAdministratorClusterTransferAnchorResponseStatus(val value: Int) {
    OK(0),
    TransferAnchorStatusDatastoreBusy(1),
    TransferAnchorStatusNoUserConsent(2),
  }

  enum class JointFabricDatastoreClusterDatastoreAccessControlEntryAuthMode(val value: Int) {
    PASE(1),
    CASE(2),
    Group(3),
  }

  enum class JointFabricDatastoreClusterDatastoreAccessControlEntryPrivilege(val value: Int) {
    View(1),
    ProxyView(2),
    Operate(3),
    Manage(4),
    Administer(5),
  }

  enum class JointFabricDatastoreClusterDatastoreGroupKeyMulticastPolicy(val value: Int) {
    PerGroupID(0),
    AllNodes(1),
  }

  enum class JointFabricDatastoreClusterDatastoreGroupKeySecurityPolicy(val value: Int) {
    TrustFirst(0),
  }

  enum class JointFabricDatastoreClusterDatastoreState(val value: Int) {
    Pending(0),
    Committed(1),
    DeletePending(2),
    CommitFailed(3),
  }

  enum class KeypadInputClusterCecKeyCode(val value: Int) {
    Select(0),
    Up(1),
    Down(2),
    Left(3),
    Right(4),
    RightUp(5),
    RightDown(6),
    LeftUp(7),
    LeftDown(8),
    RootMenu(9),
    SetupMenu(10),
    ContentsMenu(11),
    FavoriteMenu(12),
    Exit(13),
    MediaTopMenu(16),
    MediaContextSensitiveMenu(17),
    NumberEntryMode(29),
    Number11(30),
    Number12(31),
    Number0OrNumber10(32),
    Numbers1(33),
    Numbers2(34),
    Numbers3(35),
    Numbers4(36),
    Numbers5(37),
    Numbers6(38),
    Numbers7(39),
    Numbers8(40),
    Numbers9(41),
    Dot(42),
    Enter(43),
    Clear(44),
    NextFavorite(47),
    ChannelUp(48),
    ChannelDown(49),
    PreviousChannel(50),
    SoundSelect(51),
    InputSelect(52),
    DisplayInformation(53),
    Help(54),
    PageUp(55),
    PageDown(56),
    Power(64),
    VolumeUp(65),
    VolumeDown(66),
    Mute(67),
    Play(68),
    Stop(69),
    Pause(70),
    Record(71),
    Rewind(72),
    FastForward(73),
    Eject(74),
    Forward(75),
    Backward(76),
    StopRecord(77),
    PauseRecord(78),
    Reserved(79),
    Angle(80),
    SubPicture(81),
    VideoOnDemand(82),
    ElectronicProgramGuide(83),
    TimerProgramming(84),
    InitialConfiguration(85),
    SelectBroadcastType(86),
    SelectSoundPresentation(87),
    PlayFunction(96),
    PausePlayFunction(97),
    RecordFunction(98),
    PauseRecordFunction(99),
    StopFunction(100),
    MuteFunction(101),
    RestoreVolumeFunction(102),
    TuneFunction(103),
    SelectMediaFunction(104),
    SelectAvInputFunction(105),
    SelectAudioInputFunction(106),
    PowerToggleFunction(107),
    PowerOffFunction(108),
    PowerOnFunction(109),
    F1Blue(113),
    F2Red(114),
    F3Green(115),
    F4Yellow(116),
    F5(117),
    Data(118),
  }

  enum class KeypadInputClusterStatus(val value: Int) {
    Success(0),
    UnsupportedKey(1),
    InvalidKeyInCurrentState(2),
  }

  enum class LaundryDryerControlsClusterDrynessLevel(val value: Int) {
    Low(0),
    Normal(1),
    Extra(2),
    Max(3),
  }

  enum class LaundryWasherControlsClusterNumberOfRinses(val value: Int) {
    None(0),
    Normal(1),
    Extra(2),
    Max(3),
  }

  enum class LevelControlClusterMoveMode(val value: Int) {
    Up(0),
    Down(1),
  }

  enum class LevelControlClusterStepMode(val value: Int) {
    Up(0),
    Down(1),
  }

  enum class LocalizationTimeFormatClusterCalendarType(val value: Int) {
    Buddhist(0),
    Chinese(1),
    Coptic(2),
    Ethiopian(3),
    Gregorian(4),
    Hebrew(5),
    Indian(6),
    Islamic(7),
    Japanese(8),
    Korean(9),
    Persian(10),
    Taiwanese(11),
    UseActiveLocale(255),
  }

  enum class LocalizationTimeFormatClusterHourFormat(val value: Int) {
    `12hr`(0),
    `24hr`(1),
    UseActiveLocale(255),
  }

  enum class LocalizationUnitClusterTempUnit(val value: Int) {
    Fahrenheit(0),
    Celsius(1),
    Kelvin(2),
  }

  enum class MediaFileManagementClusterFileStatus(val value: Int) {
    Success(0),
    InsufficientStorage(1),
    InvalidFileID(2),
    AuthenticationFailed(3),
    FileNotAvailable(4),
    InvalidRequest(5),
    UnsupportedMimeType(6),
  }

  enum class MediaInputClusterInputType(val value: Int) {
    Internal(0),
    Aux(1),
    Coax(2),
    Composite(3),
    HDMI(4),
    Input(5),
    Line(6),
    Optical(7),
    Video(8),
    SCART(9),
    USB(10),
    Other(11),
  }

  enum class MediaPlaybackClusterCharacteristic(val value: Int) {
    ForcedSubtitles(0),
    DescribesVideo(1),
    EasyToRead(2),
    FrameBased(3),
    MainProgram(4),
    OriginalContent(5),
    VoiceOverTranslation(6),
    Caption(7),
    Subtitle(8),
    Alternate(9),
    Supplementary(10),
    Commentary(11),
    DubbedTranslation(12),
    Description(13),
    Metadata(14),
    EnhancedAudioIntelligibility(15),
    Emergency(16),
    Karaoke(17),
  }

  enum class MediaPlaybackClusterMediaType(val value: Int) {
    Generic(0),
    TVShow(1),
    Music(2),
    Podcast(3),
  }

  enum class MediaPlaybackClusterPlaybackState(val value: Int) {
    Playing(0),
    Paused(1),
    NotPlaying(2),
    Buffering(3),
  }

  enum class MediaPlaybackClusterStatus(val value: Int) {
    Success(0),
    InvalidStateForCommand(1),
    NotAllowed(2),
    NotActive(3),
    SpeedOutOfRange(4),
    SeekOutOfRange(5),
  }

  enum class MessagesClusterFutureMessagePreference(val value: Int) {
    Allowed(0),
    Increased(1),
    Reduced(2),
    Disallowed(3),
    Banned(4),
  }

  enum class MessagesClusterMessagePriority(val value: Int) {
    Low(0),
    Medium(1),
    High(2),
    Critical(3),
  }

  enum class MeterIdentificationClusterMeterType(val value: Int) {
    Utility(0),
    Private(1),
    Generic(2),
  }

  enum class Mode_DeviceEnergyManagementClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    NoOptimization(16384),
    DeviceOptimization(16385),
    LocalOptimization(16386),
    GridOptimization(16387),
  }

  enum class Mode_DishwasherClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Normal(16384),
    Heavy(16385),
    Light(16386),
  }

  enum class Mode_EVSEClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Manual(16384),
    TimeOfUse(16385),
    SolarCharging(16386),
    V2X(16387),
  }

  enum class Mode_LaundryWasherClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Normal(16384),
    Delicate(16385),
    Heavy(16386),
    Whites(16387),
  }

  enum class Mode_MicrowaveOvenClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Normal(16384),
    Defrost(16385),
  }

  enum class Mode_OvenClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Bake(16384),
    Convection(16385),
    Grill(16386),
    Roast(16387),
    Clean(16388),
    ConvectionBake(16389),
    ConvectionRoast(16390),
    Warming(16391),
    Proofing(16392),
    Steam(16393),
    AirFry(16394),
    AirSousVide(16395),
    FrozenFood(16396),
  }

  enum class Mode_RVCCleanClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    DeepClean(16384),
    Vacuum(16385),
    Mop(16386),
    VacuumthenMop(16387),
  }

  enum class Mode_RVCCleanClusterStatusCode(val value: Int) {
    CleaningInProgress(64),
  }

  enum class Mode_RVCRunClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Idle(16384),
    Cleaning(16385),
    Mapping(16386),
  }

  enum class Mode_RVCRunClusterStatusCode(val value: Int) {
    Stuck(65),
    DustBinMissing(66),
    DustBinFull(67),
    WaterTankEmpty(68),
    WaterTankMissing(69),
    WaterTankLidOpen(70),
    MopCleaningPadMissing(71),
    BatteryLow(72),
  }

  enum class Mode_RefrigeratorClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    RapidCool(16384),
    RapidFreeze(16385),
  }

  enum class Mode_ThermostatClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Off(16384),
    Cool(16385),
    Heat(16386),
    EmergencyHeat(16387),
  }

  enum class Mode_WaterHeaterClusterModeTag(val value: Int) {
    Auto(0),
    Quick(1),
    Quiet(2),
    LowNoise(3),
    LowEnergy(4),
    Vacation(5),
    Min(6),
    Max(7),
    Night(8),
    Day(9),
    Off(16384),
    Manual(16385),
    Timed(16386),
  }

  enum class NetworkCommissioningClusterNetworkCommissioningStatus(val value: Int) {
    Success(0),
    OutOfRange(1),
    BoundsExceeded(2),
    NetworkIDNotFound(3),
    DuplicateNetworkID(4),
    NetworkNotFound(5),
    RegulatoryError(6),
    AuthFailure(7),
    UnsupportedSecurity(8),
    OtherConnectionFailure(9),
    IPV6Failed(10),
    IPBindFailed(11),
    UnknownError(12),
  }

  enum class NetworkCommissioningClusterWiFiBand(val value: Int) {
    `2G4`(0),
    `3G65`(1),
    `5G`(2),
    `6G`(3),
    `60G`(4),
    `1G`(5),
  }

  enum class NetworkIdentityManagementClusterIdentityType(val value: Int) {
    ECDSA(1),
  }

  enum class NetworkIdentityManagementClusterStatusCode(val value: Int) {
    ResponseTooLarge(2),
  }

  enum class OTAProviderClusterApplyUpdateAction(val value: Int) {
    Proceed(0),
    AwaitNextAction(1),
    Discontinue(2),
  }

  enum class OTAProviderClusterDownloadProtocol(val value: Int) {
    BDXSynchronous(0),
    BDXAsynchronous(1),
    HTTPS(2),
    VendorSpecific(3),
  }

  enum class OTAProviderClusterStatus(val value: Int) {
    UpdateAvailable(0),
    Busy(1),
    NotAvailable(2),
    DownloadProtocolNotSupported(3),
  }

  enum class OTARequestorClusterAnnouncementReason(val value: Int) {
    SimpleAnnouncement(0),
    UpdateAvailable(1),
    UrgentUpdateAvailable(2),
  }

  enum class OTARequestorClusterChangeReason(val value: Int) {
    Unknown(0),
    Success(1),
    Failure(2),
    TimeOut(3),
    DelayByProvider(4),
  }

  enum class OTARequestorClusterUpdateState(val value: Int) {
    Unknown(0),
    Idle(1),
    Querying(2),
    DelayedOnQuery(3),
    Downloading(4),
    Applying(5),
    DelayedOnApply(6),
    RollingBack(7),
    DelayedOnUserConsent(8),
  }

  enum class OccupancySensingClusterOccupancySensorType(val value: Int) {
    PIR(0),
    Ultrasonic(1),
    PIRAndUltrasonic(2),
    PhysicalContact(3),
  }

  enum class OnOffClusterDelayedAllOffEffectVariant(val value: Int) {
    DelayedOffFastFade(0),
    NoFade(1),
    DelayedOffSlowFade(2),
  }

  enum class OnOffClusterDyingLightEffectVariant(val value: Int) {
    DyingLightFadeOff(0),
  }

  enum class OnOffClusterEffectIdentifier(val value: Int) {
    DelayedAllOff(0),
    DyingLight(1),
  }

  enum class OnOffClusterStartUpOnOff(val value: Int) {
    Off(0),
    On(1),
    Toggle(2),
  }

  enum class OperationalCredentialClusterAttestationCryptoProfile(val value: Int) {
    EcdsaMatterLegacy(0),
    MlDsa44(1),
    MlDsa65(2),
  }

  enum class OperationalCredentialClusterCertificateChainType(val value: Int) {
    DACCertificate(1),
    PAICertificate(2),
  }

  enum class OperationalCredentialClusterNodeOperationalCertStatus(val value: Int) {
    OK(0),
    InvalidPublicKey(1),
    InvalidNodeOpId(2),
    InvalidNOC(3),
    MissingCsr(4),
    TableFull(5),
    InvalidAdminSubject(6),
    FabricConflict(9),
    LabelConflict(10),
    InvalidFabricIndex(11),
  }

  enum class OperationalStateClusterErrorState(val value: Int) {
    NoError(0),
    UnableToStartOrResume(1),
    UnableToCompleteOperation(2),
    CommandInvalidInState(3),
  }

  enum class OperationalStateClusterOperationalState(val value: Int) {
    Stopped(0),
    Running(1),
    Paused(2),
    Error(3),
  }

  enum class OperationalState_RVCClusterErrorState(val value: Int) {
    NoError(0),
    UnableToStartOrResume(1),
    UnableToCompleteOperation(2),
    CommandInvalidInState(3),
    FailedToFindChargingDock(64),
    Stuck(65),
    DustBinMissing(66),
    DustBinFull(67),
    WaterTankEmpty(68),
    WaterTankMissing(69),
    WaterTankLidOpen(70),
    MopCleaningPadMissing(71),
    LowBattery(72),
    CannotReachTargetArea(73),
    DirtyWaterTankFull(74),
    DirtyWaterTankMissing(75),
    WheelsJammed(76),
    BrushJammed(77),
    NavigationSensorObscured(78),
  }

  enum class OperationalState_RVCClusterOperationalState(val value: Int) {
    Stopped(0),
    Running(1),
    Paused(2),
    Error(3),
    SeekingCharger(64),
    Charging(65),
    Docked(66),
    EmptyingDustBin(67),
    CleaningMop(68),
    FillingWaterTank(69),
    UpdatingMaps(70),
  }

  enum class PowerSourceClusterBatApprovedChemistry(val value: Int) {
    Unspecified(0),
    Alkaline(1),
    LithiumCarbonFluoride(2),
    LithiumChromiumOxide(3),
    LithiumCopperOxide(4),
    LithiumIronDisulfide(5),
    LithiumManganeseDioxide(6),
    LithiumThionylChloride(7),
    Magnesium(8),
    MercuryOxide(9),
    NickelOxyhydride(10),
    SilverOxide(11),
    ZincAir(12),
    ZincCarbon(13),
    ZincChloride(14),
    ZincManganeseDioxide(15),
    LeadAcid(16),
    LithiumCobaltOxide(17),
    LithiumIon(18),
    LithiumIonPolymer(19),
    LithiumIronPhosphate(20),
    LithiumSulfur(21),
    LithiumTitanate(22),
    NickelCadmium(23),
    NickelHydrogen(24),
    NickelIron(25),
    NickelMetalHydride(26),
    NickelZinc(27),
    SilverZinc(28),
    SodiumIon(29),
    SodiumSulfur(30),
    ZincBromide(31),
    ZincCerium(32),
  }

  enum class PowerSourceClusterBatChargeFault(val value: Int) {
    Unspecified(0),
    AmbientTooHot(1),
    AmbientTooCold(2),
    BatteryTooHot(3),
    BatteryTooCold(4),
    BatteryAbsent(5),
    BatteryOverVoltage(6),
    BatteryUnderVoltage(7),
    ChargerOverVoltage(8),
    ChargerUnderVoltage(9),
    SafetyTimeout(10),
  }

  enum class PowerSourceClusterBatChargeLevel(val value: Int) {
    OK(0),
    Warning(1),
    Critical(2),
  }

  enum class PowerSourceClusterBatChargeState(val value: Int) {
    Unknown(0),
    IsCharging(1),
    IsAtFullCharge(2),
    IsNotCharging(3),
  }

  enum class PowerSourceClusterBatCommonDesignation(val value: Int) {
    Unspecified(0),
    AAA(1),
    AA(2),
    C(3),
    D(4),
    `4v5`(5),
    `6v0`(6),
    `9v0`(7),
    `1_2AA`(8),
    AAAA(9),
    A(10),
    B(11),
    F(12),
    N(13),
    No6(14),
    SubC(15),
    A23(16),
    A27(17),
    BA5800(18),
    Duplex(19),
    `4SR44`(20),
    `523`(21),
    `531`(22),
    `15v0`(23),
    `22v5`(24),
    `30v0`(25),
    `45v0`(26),
    `67v5`(27),
    J(28),
    CR123A(29),
    CR2(30),
    `2CR5`(31),
    CR_P2(32),
    CR_V3(33),
    SR41(34),
    SR43(35),
    SR44(36),
    SR45(37),
    SR48(38),
    SR54(39),
    SR55(40),
    SR57(41),
    SR58(42),
    SR59(43),
    SR60(44),
    SR63(45),
    SR64(46),
    SR65(47),
    SR66(48),
    SR67(49),
    SR68(50),
    SR69(51),
    SR516(52),
    SR731(53),
    SR712(54),
    LR932(55),
    A5(56),
    A10(57),
    A13(58),
    A312(59),
    A675(60),
    AC41E(61),
    `10180`(62),
    `10280`(63),
    `10440`(64),
    `14250`(65),
    `14430`(66),
    `14500`(67),
    `14650`(68),
    `15270`(69),
    `16340`(70),
    RCR123A(71),
    `17500`(72),
    `17670`(73),
    `18350`(74),
    `18500`(75),
    `18650`(76),
    `19670`(77),
    `25500`(78),
    `26650`(79),
    `32600`(80),
  }

  enum class PowerSourceClusterBatFault(val value: Int) {
    Unspecified(0),
    OverTemp(1),
    UnderTemp(2),
  }

  enum class PowerSourceClusterBatReplaceability(val value: Int) {
    Unspecified(0),
    NotReplaceable(1),
    UserReplaceable(2),
    FactoryReplaceable(3),
  }

  enum class PowerSourceClusterPowerSourceStatus(val value: Int) {
    Unspecified(0),
    Active(1),
    Standby(2),
    Unavailable(3),
  }

  enum class PowerSourceClusterWiredCurrentType(val value: Int) {
    AC(0),
    DC(1),
  }

  enum class PowerSourceClusterWiredFault(val value: Int) {
    Unspecified(0),
    OverVoltage(1),
    UnderVoltage(2),
  }

  enum class ProximityRangingClusterBLERBCSecurityMode(val value: Int) {
    BLEDeviceIDObfuscation(0),
    EncryptedAdvertisingData(1),
  }

  enum class ProximityRangingClusterBLTCSMode(val value: Int) {
    PBROnly(0),
    RTTOnly(1),
    Both(2),
  }

  enum class ProximityRangingClusterBLTCSSecurityLevel(val value: Int) {
    BLTCSSecurityLevelUnknown(0),
    BLTCSSecurityLevelOne(1),
    BLTCSSecurityLevelTwo(2),
    BLTCSSecurityLevelThree(3),
  }

  enum class ProximityRangingClusterNADM(val value: Int) {
    AttackExtremelyUnlikely(0),
    AttackVeryUnlikely(1),
    AttackIsPossible(3),
    AttackIsLikely(4),
    AttackVeryLikely(5),
    AttackExtremelyLikely(6),
    Unknown(255),
  }

  enum class ProximityRangingClusterRDRCapability(val value: Int) {
    NoRDR(0),
    AzimuthOnly(1),
    AzimuthElevation(2),
  }

  enum class ProximityRangingClusterRDRReference(val value: Int) {
    DeviceCoordinates(0),
    EarthCoordinates(1),
  }

  enum class ProximityRangingClusterRangingRole(val value: Int) {
    WiFiSubscriberRole(0),
    WiFiPublisherRole(1),
    BLEScanningRole(2),
    BLEBeaconRole(3),
    BLTInitiatorRole(4),
    BLTReflectorRole(5),
  }

  enum class ProximityRangingClusterRangingSessionStatus(val value: Int) {
    SessionStarted(0),
    SessionEndTimeReached(1),
    SessionStoppedByRequest(2),
    PeerNotFound(3),
    HardwareError(4),
    SessionFailed(5),
  }

  enum class ProximityRangingClusterRangingTech(val value: Int) {
    BluetoothChannelSounding(0),
    WiFiRoundTripTimeRanging(1),
    WiFiNextGenerationRanging(2),
    BLEBeaconRSSIRanging(3),
  }

  enum class ProximityRangingClusterStatusCode(val value: Int) {
    RejectedInfeasibleRanging(2),
    RejectedInfeasibleRangingTriggers(3),
    BusySessionCapacityReached(4),
    BusyTryAgainLater(5),
  }

  enum class PumpConfigurationControlClusterControlMode(val value: Int) {
    ConstantSpeed(0),
    ConstantPressure(1),
    ProportionalPressure(2),
    ConstantFlow(3),
    ConstantTemperature(5),
    Automatic(7),
  }

  enum class PumpConfigurationControlClusterOperationMode(val value: Int) {
    Normal(0),
    Minimum(1),
    Maximum(2),
    Local(3),
  }

  enum class PushAVStreamTransportClusterCMAFInterface(val value: Int) {
    Interface1(0),
    Interface2DASH(1),
    Interface2HLS(2),
  }

  enum class PushAVStreamTransportClusterContainerFormat(val value: Int) {
    CMAF(0),
  }

  enum class PushAVStreamTransportClusterIngestMethods(val value: Int) {
    CMAFIngest(0),
  }

  enum class PushAVStreamTransportClusterStatusCode(val value: Int) {
    InvalidTLSEndpoint(2),
    InvalidStream(3),
    InvalidURL(4),
    InvalidZone(5),
    InvalidCombination(6),
    InvalidTriggerType(7),
    InvalidTransportStatus(8),
    InvalidOptions(9),
    InvalidStreamUsage(10),
    InvalidTime(11),
    InvalidPreRollLength(12),
    DuplicateStreamValues(13),
  }

  enum class PushAVStreamTransportClusterTransportStatus(val value: Int) {
    Active(0),
    Inactive(1),
  }

  enum class PushAVStreamTransportClusterTransportTriggerType(val value: Int) {
    Command(0),
    Motion(1),
    Continuous(2),
    AmbientContext(3),
  }

  enum class PushAVStreamTransportClusterTriggerActivationReason(val value: Int) {
    UserInitiated(0),
    Automation(1),
    Emergency(2),
    DoorbellPressed(3),
  }

  enum class ResourceMonitoringClusterChangeIndication(val value: Int) {
    OK(0),
    Warning(1),
    Critical(2),
  }

  enum class ResourceMonitoringClusterDegradationDirection(val value: Int) {
    Up(0),
    Down(1),
  }

  enum class ResourceMonitoringClusterProductIdentifierType(val value: Int) {
    UPC(0),
    GTIN8(1),
    EAN(2),
    GTIN14(3),
    OEM(4),
  }

  enum class ServiceAreaClusterOperationalStatus(val value: Int) {
    Pending(0),
    Operating(1),
    Skipped(2),
    Completed(3),
  }

  enum class ServiceAreaClusterSelectAreasStatus(val value: Int) {
    Success(0),
    UnsupportedArea(1),
    InvalidInMode(2),
    InvalidSet(3),
  }

  enum class ServiceAreaClusterSkipAreaStatus(val value: Int) {
    Success(0),
    InvalidAreaList(1),
    InvalidInMode(2),
    InvalidSkippedArea(3),
  }

  enum class SmokeCOAlarmClusterAlarmState(val value: Int) {
    Normal(0),
    Warning(1),
    Critical(2),
  }

  enum class SmokeCOAlarmClusterContaminationState(val value: Int) {
    Normal(0),
    Low(1),
    Warning(2),
    Critical(3),
  }

  enum class SmokeCOAlarmClusterEndOfService(val value: Int) {
    Normal(0),
    Expired(1),
  }

  enum class SmokeCOAlarmClusterExpressedState(val value: Int) {
    Normal(0),
    SmokeAlarm(1),
    COAlarm(2),
    BatteryAlert(3),
    Testing(4),
    HardwareFault(5),
    EndOfService(6),
    InterconnectSmoke(7),
    InterconnectCO(8),
    Inoperative(9),
  }

  enum class SmokeCOAlarmClusterMuteState(val value: Int) {
    NotMuted(0),
    Muted(1),
  }

  enum class SmokeCOAlarmClusterSensitivity(val value: Int) {
    High(0),
    Standard(1),
    Low(2),
  }

  enum class TLSClientManagementClusterStatusCode(val value: Int) {
    EndpointAlreadyInstalled(2),
    RootCertificateNotFound(3),
    ClientCertificateNotFound(4),
    EndpointInUse(5),
    InvalidTime(6),
  }

  enum class TargetNavigatorClusterStatus(val value: Int) {
    Success(0),
    TargetNotFound(1),
    NotAllowed(2),
  }

  enum class ThermostatClusterACCapacityFormat(val value: Int) {
    BTUh(0),
  }

  enum class ThermostatClusterACCompressorType(val value: Int) {
    Unknown(0),
    T1(1),
    T2(2),
    T3(3),
  }

  enum class ThermostatClusterACLouverPosition(val value: Int) {
    Closed(1),
    Open(2),
    Quarter(3),
    Half(4),
    ThreeQuarters(5),
  }

  enum class ThermostatClusterACRefrigerantType(val value: Int) {
    Unknown(0),
    R22(1),
    R410a(2),
    R407c(3),
  }

  enum class ThermostatClusterACType(val value: Int) {
    Unknown(0),
    CoolingFixed(1),
    HeatPumpFixed(2),
    CoolingInverter(3),
    HeatPumpInverter(4),
  }

  enum class ThermostatClusterControlSequenceOfOperation(val value: Int) {
    CoolingOnly(0),
    CoolingWithReheat(1),
    HeatingOnly(2),
    HeatingWithReheat(3),
    CoolingAndHeating(4),
    CoolingAndHeatingWithReheat(5),
  }

  enum class ThermostatClusterPresetScenario(val value: Int) {
    Occupied(1),
    Unoccupied(2),
    Sleep(3),
    Wake(4),
    Vacation(5),
    GoingToSleep(6),
    UserDefined(254),
  }

  enum class ThermostatClusterSetpointChangeSource(val value: Int) {
    Manual(0),
    Schedule(1),
    External(2),
  }

  enum class ThermostatClusterSetpointRaiseLowerMode(val value: Int) {
    Heat(0),
    Cool(1),
    Both(2),
  }

  enum class ThermostatClusterStartOfWeek(val value: Int) {
    Sunday(0),
    Monday(1),
    Tuesday(2),
    Wednesday(3),
    Thursday(4),
    Friday(5),
    Saturday(6),
  }

  enum class ThermostatClusterSystemMode(val value: Int) {
    Off(0),
    Auto(1),
    Cool(3),
    Heat(4),
    EmergencyHeat(5),
    Precooling(6),
    FanOnly(7),
    Dry(8),
    Sleep(9),
  }

  enum class ThermostatClusterTemperatureSetpointHold(val value: Int) {
    SetpointHoldOff(0),
    SetpointHoldOn(1),
  }

  enum class ThermostatClusterThermostatRunningMode(val value: Int) {
    Off(0),
    Cool(3),
    Heat(4),
  }

  enum class ThermostatUserInterfaceConfigurationClusterKeypadLockout(val value: Int) {
    NoLockout(0),
    Lockout1(1),
    Lockout2(2),
    Lockout3(3),
    Lockout4(4),
    Lockout5(5),
  }

  enum class ThermostatUserInterfaceConfigurationClusterScheduleProgrammingVisibility(
      val value: Int
  ) {
    ScheduleProgrammingPermitted(0),
    ScheduleProgrammingDenied(1),
  }

  enum class ThermostatUserInterfaceConfigurationClusterTemperatureDisplayMode(val value: Int) {
    Celsius(0),
    Fahrenheit(1),
  }

  enum class TimeSyncClusterGranularity(val value: Int) {
    NoTimeGranularity(0),
    MinutesGranularity(1),
    SecondsGranularity(2),
    MillisecondsGranularity(3),
    MicrosecondsGranularity(4),
  }

  enum class TimeSyncClusterStatusCode(val value: Int) {
    TimeNotAccepted(2),
  }

  enum class TimeSyncClusterTimeSource(val value: Int) {
    None(0),
    Unknown(1),
    Admin(2),
    NodeTimeCluster(3),
    NonMatterSNTP(4),
    NonMatterNTP(5),
    MatterSNTP(6),
    MatterNTP(7),
    MixedNTP(8),
    NonMatterSNTPNTS(9),
    NonMatterNTPNTS(10),
    MatterSNTPNTS(11),
    MatterNTPNTS(12),
    MixedNTPNTS(13),
    CloudSource(14),
    PTP(15),
    GNSS(16),
  }

  enum class TimeSyncClusterTimeZoneDatabase(val value: Int) {
    Full(0),
    Partial(1),
    None(2),
  }

  enum class ValveConfigurationControlClusterStatusCode(val value: Int) {
    FailureDueToFault(2),
  }

  enum class ValveConfigurationControlClusterValveState(val value: Int) {
    Closed(0),
    Open(1),
    Transitioning(2),
  }

  enum class WaterHeaterManagementClusterBoostState(val value: Int) {
    Inactive(0),
    Active(1),
  }

  enum class WindowCoveringClusterEndProductType(val value: Int) {
    RollerShade(0),
    RomanShade(1),
    BalloonShade(2),
    WovenWood(3),
    PleatedShade(4),
    CellularShade(5),
    LayeredShade(6),
    LayeredShade2D(7),
    SheerShade(8),
    TiltOnlyInteriorBlind(9),
    InteriorBlind(10),
    VerticalBlindStripCurtain(11),
    InteriorVenetianBlind(12),
    ExteriorVenetianBlind(13),
    LateralLeftCurtain(14),
    LateralRightCurtain(15),
    CentralCurtain(16),
    RollerShutter(17),
    ExteriorVerticalScreen(18),
    AwningTerracePatio(19),
    AwningVerticalScreen(20),
    TiltOnlyPergola(21),
    SwingingShutter(22),
    SlidingShutter(23),
    Unknown(255),
  }

  enum class WindowCoveringClusterType(val value: Int) {
    RollerShade(0),
    RollerShade2Motor(1),
    RollerShadeExterior(2),
    RollerShadeExterior2Motor(3),
    Drapery(4),
    Awning(5),
    Shutter(6),
    TiltBlindTiltOnly(7),
    TiltBlindLiftAndTilt(8),
    ProjectorScreen(9),
    Unknown(255),
  }

  enum class ZoneManagementClusterZoneEventStoppedReason(val value: Int) {
    ActionStopped(0),
    Timeout(1),
  }

  enum class ZoneManagementClusterZoneEventTriggeredReason(val value: Int) {
    Motion(0),
  }

  enum class ZoneManagementClusterZoneSource(val value: Int) {
    Mfg(0),
    User(1),
  }

  enum class ZoneManagementClusterZoneType(val value: Int) {
    TwoDCARTZone(0),
  }

  enum class ZoneManagementClusterZoneUse(val value: Int) {
    Motion(0),
    Privacy(1),
    Focus(2),
  }
}
