# SPDX-FileCopyrightText: 2026 The Authors
# SPDX-License-Identifier: Apache-2.0

name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build and run tests
        run: ./gradlew -PselectedAbi=arm64-v8a assemble test
      - name: Upload APK artifact
        uses: actions/upload-artifact@v7
        with:
          name: aether-artifacts
          path: app/build/outputs/apk/*/*.apk
