# SPDX-FileCopyrightText: 2026 The Authors
# SPDX-License-Identifier: Apache-2.0

name: Code Scanning

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "30 6 * * 1"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  code-ql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java-kotlin
          queries: security-extended
      - name: Build for CodeQL
        run: ./gradlew assemble --no-daemon --parallel
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  format-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Download Kotlin formatter
        uses: robinraju/release-downloader@v1
        with:
          repository: facebook/ktfmt
          fileName: ktfmt-*-with-dependencies.jar
          latest: true
      - name: Format Kotlin scripts and source files
        run: |
          java \
            -jar ktfmt-*-with-dependencies.jar \
            $(find . -name "*.kt" -o -name "*.kts")
      - name: Check for formatting violations
        run: git diff --exit-code

  format-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Download Python formatter
        run: pip install ruff
      - name: Format Python scripts
        run: ruff format --quiet .
      - name: Check for formatting violations
        run: git diff --exit-code

  lint-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Run Android linter
        run: ./gradlew :app:lint --no-daemon --parallel
      - name: Annotate with Android linter results
        uses: yutailang0119/action-android-lint@v5
        with:
          report-path: app/build/reports/*.xml
          ignore-warnings: false

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Download Python linter
        run: pip install ruff
      - name: Run Python linter
        run: ruff check .

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
