# SPDX-FileCopyrightText: 2026 The Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      target:
        description: "Gradle task to run for manual builds"
        default: assembleRelease
        type: choice
        options:
          - assembleRelease
          - assembleDebug
      abi:
        description: "Target ABI"
        default: arm64-v8a
        type: choice
        options:
          - arm64-v8a
          - x86_64

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Restore keystore from GitHub Secrets
        env:
          # To regenerate this key and rotate the secret:
          # > keytool -genkeypair -v -keystore debug.keystore -storetype PKCS12 \
          #     -storepass android -alias androiddebugkey -keypass android \
          #     -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          # base64 -w 0 debug.keystore | gh secret set DEBUG_KEYSTORE_B64
          DEBUG_KEYSTORE_B64: ${{ secrets.DEBUG_KEYSTORE_B64 }}
        run: |
          mkdir -p $HOME/.android
          echo $DEBUG_KEYSTORE_B64 | base64 -d > $HOME/.android/debug.keystore
      - name: Build APK
        run: |
          ./gradlew \
            -PsigningConfig=persistentDebug \
            ${{ inputs.abi && format('-PselectedAbi={0}', inputs.abi) || '' }} \
            ${{ inputs.target || 'assembleRelease' }}
      - name: Upload APK artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v7
        with:
          path: app/build/outputs/apk/*/*.apk
          archive: false
      - name: Create new release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: app/build/outputs/apk/*/*.apk
          prerelease: false
          draft: false
